### ISSUE TITLE
Save error: Mac OX: window titlebar visual unsaved state indicator persists after save

### ISSUE THREAD

**Issue by ecossette** [inkle/inky#108]
When I save an open Ink file, the black dot in the red close button persists in the Inky titlebar, i.e., suggest I have unsafe changes. But in finder, the last modified time stamp will reflect my save attempt.

If I try to close the file, I will get the "you have unsaved changes message." Saving from this window doesn't remove the black dot/unsaved changes either. 

If I ignore the "unsaved changes" message and choose to close the file, when I reopen it my changes are there. 

I've tried:
- Restart my Mac
- Run disk utility first aid.
- Reinstall Inky

I'm on:
Mac OS Sierra 10.12.6
iMac Retina 5k, 27 inch

Problem is not evident in any other application.

**Comment by snarlynarwhal** [comment]
I can confirm that the save appears to stop working for some files on Windows 10 64-bit also. However, when I re-open the project, my unsaved files get lost completely.

**Comment by joethephish** [comment]
Sorry, little bit confused about what the exact repro steps are here. In a minimal single-file project and also simple include file cases I'm not managing to repro this bug. Similarly with basic repro attempts in a large project.

If possible, would you mind giving details repro steps and/or a screencast that demonstrates the problem, hopefully with as simple a project as possible? Thanks!

**Comment by joethephish** [comment]
Ah, never mind, got repro steps when attempting to follow the start if #110's repro steps:

1. Create new project (create a main.ink and save it in a folder)
2. Create an include file called `intro/intro`.
3. Enter some text in it.
4. Save.

File isn't created in finder, and filename stays bold in sidebar, though text is compiled into story okay in play view.

**Comment by joethephish** [comment]
As suggested by @snarlynarwhal, this is when a subdirectory doesn't exist yet. Fixed in e8608c89e99fc4a53234440d60b2d2edff9452aa, will go into next build.

**Comment by snarlynarwhal** [comment]
Awesome, thanks so much for the speedy replies and fix!
