### ISSUE TITLE
Show version number

### ISSUE THREAD

**Issue by mehalon** [inkle/inky#115]
Hi, 
could you add an "About" window to the help drop-down menu telling you which version you are currently using? I am not sure which version I am using and when I should update.

**Comment by joethephish** [comment]
There already is on the Mac version (in the Inky menu). I guess that menu is different on windows then and inaccessible.

**Comment by mehalon** [comment]
I'm using Windows 10, yes.

**Comment by joethephish** [comment]
Assigning the help wanted label - would be happy to accept pull requests for plumping in the about box into the windows version.

For explanation of how it works on Mac:

 * In `appmenus.js`, there's a Mac-specific Inky menu with an "About Inky..." item - search the file for `callbacks.showAbout`.You just need to plumb this in to a Windows-specific menu somewhere appropriate to the platform.
 * The main logic for the internals of the about window is in `aboutWindow.js`.
 * And the view is in `renderer/about/about.html`.

It's designed to look like a Mac standard one + extra version numbers, but I'm sure Windows people wouldn't mind to  much about that!

**Comment by allaze-eroler** [comment]
hello, there is a small error in the new version of inky 0.9.0, it said this:

```
Inky version: 0.8.0
ink version: 0.8.0
inkjs version: 1.6.0
```
which mean the software still display as 0.8.0 instead of 0.9.0

despite of that, the about inky work like a charm on my windows 7 pro 64bits!

**Comment by joethephish** [comment]
Ooops sorry, forgot to bump the internal version number. Have just fixed this and updated the binary builds on the releases page!

**Comment by I2oy** [comment]
Was looking at the list of open Help Wanted issues. This one seems to be solved. Should this one be closed, @joethephish ?

**Comment by joethephish** [comment]
Ah yes, thanks!
