### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by MrBrits** [inkle/inky#117]
Hello all,

I only started using Inky and so far I really find it very helpful, but something I always look for in any development environment is some form of dark theme to be a bit easier on the eyes after long hours.

**Comment by advgamer** [comment]
yes please!

**Comment by allaze-eroler** [comment]
apparently the dark theme is not working since the update of inky 0.10.0....

**Comment by joethephish** [comment]
Note that the dark theme mentioned in the release notes of inky 0.10.0 is for the web template, not for inky itself.

**Comment by lunarcloud** [comment]
Well both editor and export versions of dark theme work in the source code right now.
