### ISSUE TITLE
Feature request: Visual dialogue tree

### ISSUE THREAD

**Issue by TomoCZ** [inkle/inky#121]
It took me almost one year to find this great game screenplay writing software/language that suits my needs unlike others, even not free and totally profesional programs.

Anyway, in order to help in orienting in long and complex scripts it would be awesome to have a posibility to generate some sort of visual dialogue tree. Not for manipulating and editing the branches or something (that would be too much to ask), but just for beeing able to view it which would help author and more the others in team to better orient in the branches.

Tank you for doing a great job. :)

**Comment by Tom-Julux** [comment]
The problem with this is the complexity of ink. You can create hundreds of possibilities with only a handful of lines

**Comment by y-lohse** [comment]
FWIW I've done a little work on that [here](http://yannick-lohse.fr/graphink/). It's very hacky and def. not production grade but maybe it can help you.

**Comment by TomoCZ** [comment]
y-lohse: Thats exactly what I had in mind! But it seems I cant get it work... The Intercept example works fine but when I load my own .json file, nothing happens. Any idea what am I doing wrong?

**Comment by y-lohse** [comment]
Not really, but if there was an error you can probably see it in the browser's console. It's very possible that there are bugs lft to be fixed in it :(
I'll also say right away that I don't really maintain that code, but you're free to use it for whatever you want!

**Comment by TomoCZ** [comment]
What a pitty you dont continue working on this, because I think its a great base for building really great tool! :) 
Thank you for your permission, I might try to dig into it later when I have more time, but I am not sure if I will be able to really do something with that. My programming/scripting skills are pretty much basic, so... :/

**Comment by joningold** [comment]
Apologies, but we're highly unlikely to add this to the main inky codebase. It's too tricky to well due to the innate complexity of the language. It's probably better to maintain a master flow chart of your own in another tool, and write to fit that, if that's what you need to do.

**Comment by allaze-eroler** [comment]
there is actually a solution that you could do without touching too much the ink scripting, all we need to do is to use this CSS codes that i found [there](http://thecodeplayer.com/walkthrough/css3-family-tree), as you might noticed, it doesn't need any flash or javascript, only done with CSS. so i think it's a viable solution to this problem. sorry if i took long time to bring this solution because i was too looking for this system.
