### ISSUE TITLE
Feature request: pause auto-compilation for when you're doing a lot of work

### ISSUE THREAD

**Issue by joningold** [inkle/inky#13]
Sometimes if I'm working on something a little involved, the auto-compilation - and in particular, the auto-replay - gets annoying, as it flashes up errors and rescrolls the window. It'd be nice to be able to pause it. (Perhaps this only pauses the replay, actually?)

**Comment by joethephish** [comment]
Although this is a pretty easy task to implement, it should be unnecessary.

Once, #17 is done it probably won't be necessary. Once the player view stops flashing after small changes, it'll be less distracting.

Furthermore, generalising the concept of #18, we could allow you to go into a single-pane mode, which is effectively the same thing as this task.
