### ISSUE TITLE
Linux: support for running without WINE?

### ISSUE THREAD

**Issue by nmstoker** [inkle/inky#145]
From what I can understand of the way this works, it seems odd to require WINE for Linux users.

It needs to run inklecate, which is written in .Net (C#  think) and so the suggestion is to emulate being on a Windows machine.  But when I check here, https://github.com/inkle/ink I see that there are instructions for Linux users to run inklecate with Mono (ie to run .Net on Linux).

Couldn't Linux users just follow the inklecate Linux instructions and then the rest would be fine (it looks like the rest of inky is done with electron, so already cross platform). Would then just need a tiny tweak so that it calls inklecate (rather than the Windows .exe)

I'll have a go when I'm done with work later on to see if I can actually use it this way and if so, I'll update details here.

Another option (which is perhaps something to raise in the inklecate repo instead) is whether it might run on .Net Core 2 on Linux instead/as well, since that's an MS-supported open source alternative to Mono now.  I happen to have it installed for another project, so might give it a shot.

Is there any advice from the inky developers on these points?

Thanks,
Neil

**Comment by joethephish** [comment]
Hey! I'm the primary Inky developer. I have close to zero opinion on Linux, so knock yourself out! @kennethlarsen is my go-to contact for opinions on Linux matters :)

**Comment by kennethlarsen** [comment]
Please have a go at this! We had quite some issues with getting inklecate to run on different Linux distros but I think your approach sounds right.

**Comment by nmstoker** [comment]
Thank you both.  **Good news:** I'm making progress :smile: 

I think the .Net Core approach will need to wait for another day (looked like I'd need to change a fair few things beyond my basic familiarity with .Net given it's years since I've coded with it)

However I  was able to get inklecate built with mono only, ie no WINE.  It runs a test .ink file I created on the command line, so that part is good.

Right now am just trying to get round the point about inky not realising to run mono, and I'm probably pretty close but not quite there yet.

I'll update if (_when_) I get it working.  It's probably worth me going over the steps again just to ensure I get down to the absolutely minimal steps (ie w/o a couple of wrong turns I tried!) before I write up, but I took reasonable notes as I  went.  I'm on Arch Linux, but if I get time I'll probably be able to try in a Debian or Ubuntu VM too (some steps are bound to differ subtly)

**Comment by nmstoker** [comment]
I managed to get it running using mono for inklecate (and not needing wine).

I used a two line script as described here: http://www.mono-project.com/archived/guiderunning_mono_applications/#shell-scripts

That meant just needed a small chance in the inklecate.js file from inky (to point to that script) and it worked fine. Will write up properly over the weekend when I get a chance

**Comment by kennethlarsen** [comment]
That's great! Thanks a lot @nmstoker. And if you do get the time to verify the solution on a Debian based system that would be amazing.

**Comment by nmstoker** [comment]
Here are the full instructions as used on a fresh **Ubuntu 16.04 LTS** VM installation

* **_As part of VM install (suspect it makes little difference here)_**
`sudo apt-get install -y dkms build-essential linux-headers-generic linux-headers-$(uname -r)`

* **Pre-requisites**
`sudo apt install git`
`sudo apt install curl`

* **Install node and npm**
`curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -`
`sudo apt-get install -y nodejs`

* **Test versions**
`nodejs --version`
`npm --version`

* **Install mono** as per http://www.mono-project.com/download/stable/#download-lin
`sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF`
`echo "deb http://download.mono-project.com/repo/ubuntu stable-xenial main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list`
`sudo apt-get update`
`sudo apt-get install mono-complete`

* **Install inky**
`git clone https://github.com/inkle/inky.git`
`cd inky/app/main-process/ink`

* **Basic test with mono** (should output usage info)
`mono inklecate_win.exe`

* **Create test.ink file**
`nano ~/test.ink`

* **Paste following lines:**

```
Hello world!
*	Hello back!
		Nice to hear from you!
-> END
```

* **Exit with ctrl-X then Y**

* **Run with the test.ink file and confirm output**
`mono inklecate_win.exe -p ~/test.ink`

* **Fix it in inky:** method uses a script as per here: http://www.mono-project.com/archived/guiderunning_mono_applications/
* **Create script in nano then paste in the two lines below**
`nano inklecate_linux`

>#!/bin/sh
>/usr/bin/mono inklecate.exe "$@"

* **Make it executable**
`chmod +x inklecate_linux`

* **Try it and see expected output as above**
`./inklecate_linux -p ~/test.ink`

* **Now update repo to work with inklecate_linux**
`cd ..`
`nano inklecate.js`

* **Edit:** on line 15, change this ...
`"linux": "/ink/inklecate_win.exe"`
* to this ...
`"linux": "/ink/inklecate_linux"`
* **Exit with ctrl-X then Y**

* **Now test inky**
`cd ../..`
`./INSTALL_AND_RUN.command`

This should open properly and can be used just as with the Windows and Mac versions.

There does seem to be a recurring Javascript error upon closing, but it's not critical (just annoying as comes up about fifteen times in a row!)

**Comment by kennethlarsen** [comment]
@nmstoker Great work, thanks! Would you mind creating a PR updating the README with a section on using Inky without Wine? And then link to your issue comment? (https://github.com/inkle/inky/issues/145#issuecomment-374071172)

**Comment by nmstoker** [comment]
Sorry for the delay @kennethlarsen. Sure, I'll get on to that soon (won't be this weekend, but hopefully by end of next week)

**Comment by kennethlarsen** [comment]
@nmstoker Thanks a lot!

**Comment by Jantho1990** [comment]
I just followed the steps for these. It worked, except for the `inklecate_linux` script it should be as follows:
```
#!/bin/sh
/usr/bin/mono inklecate_win.exe "$@"
```
There is no `inklecate.exe`

**Comment by nmstoker** [comment]
Glad it worked @Jantho1990 - and sorry about that small inklecate.exe mistake
I fixed that in the PR I just submitted and will edit it above (just in case anyone follows instructions above before PR included)

**Comment by kennethlarsen** [comment]
Since this has been merged the issue can now be closed.
