### ISSUE TITLE
Web Export - Player Hyperlinks

### ISSUE THREAD

**Issue by SirMetathyst** [inkle/inky#146]
Say I have a chapter of something and I want to split up a "book" into multiple web pages. How can export to web but create a hyperlink in the text of the story to some web page and also be able to create a hyperlink to a web page which is a choice. for example:

"The robot drew near to the spaceship" [link to webpage]text

- Destroy It (hyperlink to a webpage).
- Walk past it.

is that possible? If not, what would I need to change to make this work (assuming this would need to be done in js engine or something)

EDIT:
Could implement this in unity easily though (crap at js) but I like the scroll effect and the text being added to the end of a webpage which I can't get if I export to webgl with unity as far as I know.

**Comment by y-lohse** [comment]
It's not possible directly with ink, so yes, you'd have to tweak things a bit — but not the js engine itself.

You'll want to include some sort of marker with the choice text, like a special syntax:

```
- [markdown style](/battle.html)
- custom thing -> /battle.html
```

And then in js, [when you retrieve the text](https://github.com/inkle/inky/blob/master/app/export-for-web-template/main.js#L55), you parse out the choice text and watch out for these markers.

**Comment by SirMetathyst** [comment]
This is what I changed it to using '+' as a separator.

```javascript
            var choiceParagraphElement = document.createElement('p');
            choiceParagraphElement.classList.add("choice");
            var s = choice.text.split("+")
            var link = ""
            if (s[1] != undefined){
                link = "http://" + s[1]
            }
            choiceParagraphElement.innerHTML = `<a href='${link}'>${s[0]}</a>`
            storyContainer.appendChild(choiceParagraphElement);
             ...
```

and it contains the link I want but it doesn't navigate to it...

**Comment by y-lohse** [comment]
Oh right, I didn't see the template was already using links. It doesn't work because [click events are canceled](https://github.com/inkle/inky/blob/master/app/export-for-web-template/main.js#L68) afterwards. But you could change that code to only cancel the event when the link's target is not a different URL.

**Comment by SirMetathyst** [comment]
Yup, figured it out as you sent that. Changed it to this:

```javascript
            // Click on choice
            var choiceAnchorEl = choiceParagraphElement.querySelectorAll("a")[0];
            choiceAnchorEl.addEventListener("click", function(event) {
                
                if (s[1] == undefined) 
                {
                    // Don't follow <a> link
                    event.preventDefault();

                    // Remove all existing choices
                    var existingChoices = storyContainer.querySelectorAll('p.choice');
                        for(var i=0; i<existingChoices.length; i++) {
                        var c = existingChoices[i];
                        c.parentNode.removeChild(c);
                    }

                    // Tell the story where to go next
                    story.ChooseChoiceIndex(choice.index);

                    // Aaand loop
                    continueStory();
                }
            });
        });
```
and now everything works as expected. Thank you for your help! :)
