### ISSUE TITLE
0.9.0 Ubuntu - compiler has two errors with inklecate_win.exe

### ISSUE THREAD

**Issue by Jantho1990** [inkle/inky#147]
I'm not sure if these two errors are related or not, so I'll post them both here, and if it's determined they need to be listed as separate issues I can update.

Just installed the latest 0.9.0 version of Inky. Followed the instructions for a Linux install. The program starts fine, but the preview side shows this:

```
/path/Inky-linux-x64/resources/app.asar.unpacked/main-process/ink/inklecate_win.exe: 1: /path/Inky-linux-x64/resources/app.asar.unpacked/main-process/ink/inklecate_win.exe: MZ����@���: not found
/path/Inky-linux-x64/resources/app.asar.unpacked/main-process/ink/inklecate_win.exe: 2: /path/Inky-linux-x64/resources/app.asar.unpacked/main-process/ink/inklecate_win.exe: Syntax error: "(" unexpected
```

> /path = the path to the project directory

Making any edits on the editor side results in a refresh of the preview side and the same error text above.

This is my first time trying to install Inky, am planning on installing an earlier release to see if it has the same issues.

**Comment by Jantho1990** [comment]
Following the instructions for installing on Linux without WINE in #145 resulted in the app working as expected!

**Comment by kennethlarsen** [comment]
Nice! This issue can be closed then.
