### ISSUE TITLE
Request for 32 bit Linux build

### ISSUE THREAD

**Issue by kevinkoosk** [inkle/inky#156]
Hi, I've just come across Inky, and I'm hoping to give it a try. I'm using a rather old but trusty 32 bit laptop that runs on Linux. I see that there is a 32 bit build for Windows, but only a 64 bit build for Linux. Any chance that you could compile a 32 bit build for Linux as well? Thanks!

**Comment by lunarcloud** [comment]
Not possible I tried to implement a 32-bit build and got this:
`WARNING: Official linux/ia32 support only exists in Electron < 4.0.0-beta.1`

Also, with Linux distributions like Ubuntu dropping support for 32-bit, this doesn't make sense to implement anymore.
