### ISSUE TITLE
Web export doesn't work on linux

### ISSUE THREAD

**Issue by louckousse** [inkle/inky#158]
When I want to use the `Export for web` I get this error.
![image](https://user-images.githubusercontent.com/6485933/44282421-477e8e00-a25b-11e8-9822-689b77957460.png)

However the file is present in `resources/app.asar.unpacked/main-process/ink` directory, so I just copy/past from there to the expected location and it works just fine.

**Comment by joethephish** [comment]
Thanks for the report - have done as you said and put another copy of the file in the inkjs-compatible directory: d8f68fffc8c02376c2bebd1d821fda3e67730b8f.
