### ISSUE TITLE
inky window close order problem

### ISSUE THREAD

**Issue by majorika** [inkle/inky#16]
When inky started, we have a clean, empty window.
Open exist a ink file, and close first empty window.
Then other window can't be closed. I have to use 'force quit'.

![gif](https://cloud.githubusercontent.com/assets/5467150/16232923/6487ae98-3807-11e6-9ec5-36d4b4abe591.gif)

**Comment by joethephish** [comment]
Ah, thanks for the report. I'd seen this a few times but wasn't sure of a solid repro.

**Comment by joethephish** [comment]
And fixed in 910295cb48acbf56d9037f1e01a6505a7b5ad2ab!
