### ISSUE TITLE
Inky 0.10.0 froze and became unresponsive.

### ISSUE THREAD

**Issue by fragmental** [inkle/inky#164]
Here is a screenshot of inky after the freeze.
https://i.imgur.com/mlLBy4X.jpg
I had just played the story from the beginning and selected either "search" or "darkness" when inky froze.  I was able to access the menus, but there was no response when selecting menu options.  The cpu usage slowly increased until it was taking up all the cpu that was free.  I was forced to shut down the program through the Task Manager.  I lost all of my progress, because I had not saved.  I didn't know I needed to.

I'm on windows 10 x64 and was using Inky-win32-x64 0.10.0

**Comment by joningold** [comment]
I can’t see from the resolution of the screenshot but is it possible you
put the story into an infinite loop? That can lock up the player pane (and
it’s only really fixable by using the double rewind arrow to scroll the
story up and waiting for it to manage to do it).

Jon

**Comment by fragmental** [comment]
You were correct.  I was putting it an infinite loop because I was missing the choice bullets.  I wish there was a better way to recover from an infinite loop, though.  the double rewind arrow did not respond.

As for the image, I'm guessing you're on some kind of mobile browser.  Imgur is being dumb lately and forwarding image links to their website, which only shows a tiny low res thumbnail with no way to see the full size image.  I think it's an attempt to encourage people to download their app, because it makes no sense otherwise.  The image itself is something like 1800x700.  You can request the desktop version and that will give you the full size image.

**Comment by joningold** [comment]
Yeah. The tighter the loop the worse it is; in our game the ink is huge;
compilation is quite slow; so if you insert a rogue character into the ink
you can crash the compiler and stop the flow - but in a short script that’s
harder.

Better coping with infinite loops is on the list! But we won’t have much
time to look at new features until Heavens Vault ships. (Obvs we’d welcome
community work here!!)

**Comment by fragmental** [comment]
@joningold Thanks for your help.  I'll go ahead and close this issue, now.
