### ISSUE TITLE
Can't Upload Game to Kongregate

### ISSUE THREAD

**Issue by vizthex123** [inkle/inky#165]
This issue is caused because Kongregate doesn't accept .js files, and the .html just goes to the main website.

Is there a way you could let us export files as .swf or make the main game export as a .html?

**Comment by lunarcloud** [comment]
According to https://docs.kongregate.com/docs/uploading-your-game
"**Additional Files** is an option to upload a .zip with supplemental files to your base .html or .swf loader."

Just zip up the other files, check the "I would like to upload additional files for this game" and upload them that way.

Hope that helps. 
Recommend you close this issue.

**Comment by vizthex123** [comment]
yeah this is irrelevant now, and i completely forgot i even posted it.
