### ISSUE TITLE
Feature request: prevent player window jumping when refreshing

### ISSUE THREAD

**Issue by joningold** [inkle/inky#17]
Having played through a longish story, when the story reloads / replays, it rebuilds itself from the beginning and so scrolls. This happens repeatedly as you type. But, generally, it returns to exactly the same state as before! So would it be possible to delay the refresh of the window until the new story has been run, and then switch over, to avoid the distracting jumping?

**Comment by joethephish** [comment]
Yup, this could definitely do with some improvement!

**Comment by joethephish** [comment]
This is now fixed in https://github.com/inkle/inky/tree/smooth-playerView-refresh, but I'm just investigating whether I accidentally introduced new slowdown or whether it's an unrelated issue.

**Comment by joethephish** [comment]
Looks like it was unrelated. New build uploaded here: https://github.com/inkle/inky/releases/tag/0.2.2
