### ISSUE TITLE
New functions (floor, ceiling) fail on web/js export

### ISSUE THREAD

**Issue by doskey321** [inkle/inky#172]
Hi, 
I am using the newer floor and ceiling functions and when previewed in Inky (0.10.0), they work fine and round values as they should do. However, the web and js export apparently fail because of their usage:

![error](https://user-images.githubusercontent.com/43860422/47440599-2d12e480-d7b7-11e8-9c5f-3011fa9363e8.png)
The exact error message is: function call target not found: '-> floor' / '-> ceiling' etc

I could replicate this on the linux and both win64/32 versions. JSON export works fine though and e.g. with the current github of the unity integration package there are no problems with my story files.

Ink script
```
== function round (x) ==
// Uses INKS 0.8.2 newly added ceiling/floor functions
~temp int_val = 0
~int_val = INT(x) + 0.5


{
- int_val > x: 
~int_val = FLOOR(x)
- else: 
~int_val = CEILING(x)
}

~return int_val
```

**Comment by joningold** [comment]
These functions aren’t implemented yet in ink-js, which tends to be a
version behind. :(

**Comment by lunarcloud** [comment]
It's working now with the 0.12.0 Inky web exports.
Recommend close.
