### ISSUE TITLE
Clear and Restart tags don't seem to function

### ISSUE THREAD

**Issue by nicholasderk** [inkle/inky#176]
Perhaps it is unclear where to place the tags, but I've tried many different combinations and it does not seem to perform the behaviour referenced in the Release notes (unlike the dark theme and byline tags which do work, but in my experience only if they are the first things in the .ink file)

**Comment by evangelinepapanicola** [comment]
I'm also finding this - I noticed the # CLEAR addition in the release notes and thought I'd give it a try myself as it would be useful for the game I'm working on, but I couldn't get it to do anything... here is the markup in the file I used to test, perhaps I'm using it wrong?

```
Hello
* Choice 1
* Choice 2

# CLEAR

- Hello 2

* Choice 3
* Choice 4

- ->END
```

**Comment by evangelinepapanicola** [comment]
Actually, this works for me! The tags should be inline (I'm silly)

```
Hello
* Choice 1
* Choice 2

- Hello 2 # CLEAR

* Choice 3
* Choice 4

- ->END
```

**Comment by joethephish** [comment]
This was simply because:

```
* Choice 2

    # CLEAR

- Hello 2
```

...is putting the tag in the "choice 2" section (I added indentation for clarity). This should work:

```
* Choice 2

-
# CLEAR
Hello 2
```

**Comment by lunarcloud** [comment]
Sounds like this issue can be closed. 
Easy mistake to make with blank lines and tags.
