### ISSUE TITLE
Knob parameters and local variables not found

### ISSUE THREAD

**Issue by joaobsneto** [inkle/inky#183]
I build a complete game with an older version version of ink. When I upgrade to this current version, I got a lot of erros, but I think the main reason was a pattern that I used of knobs with divert parameters. I created a new project to try out and found this "maybe bug" or change of syntax.

```
=== INTERACTION_KEY (-> go_back)===
~temp IS_LOCKED = true
+[TRY TO OPEN]
	{
	-IS_LOCKED :
		It's locked
		->go_back
	-else:
		->GET_ITEM
	}

=GET_ITEM
    You got a new sword!
		-> go_back
```
The 'go_back' divert inside GET_ITEM is not found.
In the previous versions this used to work fine.

**Comment by joningold** [comment]
We tightened up the restrictions on temp variabls, because in cases like
the one you quoted, it was possible for the value to get lost during the
flow causing errors. The fix is tedious but easy; you need to pass the
parameter along

-> GET_ITEM(go_back)

...

= GET_ITEM (-> go_back)

....

**Comment by joaobsneto** [comment]
Ow, thanks! That's make sense.
I used to have problems passing divert reference in Knobs in previous versions, was it fixed?
The last version is more stable and fast. Congratulations!
