### ISSUE TITLE
Inky first run should start with a demo story! :)

### ISSUE THREAD

**Issue by skhameneh** [inkle/inky#189]
It would be great to have a nice demo pre-loaded on first run!

**Comment by katafrakt** [comment]
Are we talking about [this](https://github.com/inkle/inky/blob/master/app/renderer/test.ink) story or is there some other demo?

**Comment by jeremydouglass** [comment]
If it was for a pre-loaded story on the first run then I would assume that it would be something more substantial -- not a testing stub, but a short demo of that showcases several basic features.

**Comment by katafrakt** [comment]
I agree. But it makes two issues out of one:

1. Someone has to create this story
2. Someone has to add loading it on the first run

**Comment by electavire** [comment]
Is this still something people would be interested in? I really like the idea of having the interactive story explain what different aspects of Ink/Inky are as you go, and I'd be happy to try and make it myself.  I had an idea that rather than be on first run only, there could be a menu option to open the tutorial story.  Sound good?

**Comment by Liance** [comment]
That doesn't sound like a bad idea at all - there's currently a way in latest build of Inky to load The Intercept from menu, but there's definitely a huge gulf between "No story at all" and "The Intercept" where a tutorial story would come in handy.

![image](https://user-images.githubusercontent.com/3412295/83346626-1b3fde80-a316-11ea-96e1-3f89b3668afb.png)

**Comment by jeremydouglass** [comment]
Quill uses "The Wager" as a short story.

http://jeejah.xyz/quill/

**Comment by Liance** [comment]
With the help of sleepysappho and gavinsta on the discord channel, I've written up an intro story!
It can be found on [Quill here](http://jeejah.xyz/quill/play/1q443qqgtcx), or you can access and run the Ink yourself from [this gist](https://gist.github.com/Liance/75ed80b8488f35a4ad3f05126eb64abf).

I based it off The Wager. I think it runs a little long, but it fits within a single page of Inky, and it should be easy to cut things from it. It demonstrates some core Ink features, and I think it's relatively easy in this example to draw relationships between what's going on in the Ink story and the actual game, even for a new user.

Loading it up on a fresh run of Inky should be relatively easy - that should be a matter of replacing the default "Once upon a time..." text that currently appears.
![image](https://user-images.githubusercontent.com/3412295/84580757-baaea800-add1-11ea-8f04-077b82efe714.png)

I'm also wondering if we should load Inky with a shortened version of this story (closer in length to the wager), and put this story alongside The Intercept as an example Ink story that can be loaded from the snippets menu.

![image](https://user-images.githubusercontent.com/3412295/84580826-a4551c00-add2-11ea-8dcc-9e6a95ee558e.png)

**Comment by lunarcloud** [comment]
Considering that not only is "The Intercept" there, but in development, they're adding more example stories,
![image](https://user-images.githubusercontent.com/1565970/149195647-22c5be6c-9f22-4ab5-af99-828a68525d1b.png)
Pontoon Game: 6f6ec7f07244c1652a4fc8cb02f380e898a6065e
Crime Scene: 1ab48716f69d6142ddb931839c3f7b672494af2b

I think we can consider this added, eh?
