### ISSUE TITLE
Javascript exception when new project is created.

### ISSUE THREAD

**Issue by ievgennaida** [inkle/inky#196]
Inky

Inky version: 0.10.0
ink version: 0.8.2
inkjs version: 1.7.1 with hotfix
windows 64
1. Open the app. 
2. Open left menu bar.
3. File - new project
4. Close new created window.

"object has been destroyed"

**Comment by katafrakt** [comment]
Can confirm the same on linux, both in the latest version downloaded from releases and built manually from git.

**Comment by lunarcloud** [comment]
I've seen it when closing any project on Linux
