### ISSUE TITLE
Commenting text color is too close to code text color

### ISSUE THREAD

**Issue by dithyrambs** [inkle/inky#201]
![image](https://user-images.githubusercontent.com/37421414/62261491-5c9bf080-b3ca-11e9-9f34-15dd406db2aa.png)

We were just banging our head against the wall for a while, not realizing that just one line of uncommented code was hiding among a swath of commented code.

<3 Inky and you guys, but this is driving me insane.

**Comment by I2oy** [comment]
I noticed that too, and created a pull request to see how we can resolve this.

**Comment by dithyrambs** [comment]
Awesome, thanks! ^<^
