### ISSUE TITLE
How to make sticky choices disappear

### ISSUE THREAD

**Issue by TheFoxWithTheCandle** [inkle/inky#204]
Hi folks,

I am pretty new to ink, but I enjoy it really much so far. But I have a problem for which I could not find a solution (yet). 
Is it possible to make a sticky choice disappear, after it has been chosen for a certain amounts of time (e.g. three times), so that only one option remains after a while?

=opts
+[Option 1] {First choice|Second choice|Third choice} ->opts
+[Option 2] {First choice|Second choice|Third choice} ->opts
+[Option 3] ->nextknot

Thanks for your help, 
a Fox with a Candle

**Comment by joningold** [comment]
```
=opts
+ (opt1) {opt1 < 3} [Option 1] {First choice|Second choice|Third choice} ->opts
+ (opt2) {opt2 < 3}  [Option 2] {First choice|Second choice|Third choice} ->opts
+[Option 3] ->nextknot
```
Two things - firstly giving each choice an explicit label so it can be tracked; then adding a conditional that says "only show this if this choice has a read-count of less than 3" - ie. the output of this choice has been seen less than 3 times.

**Comment by TheFoxWithTheCandle** [comment]
Great! Thank you very much :)
