### ISSUE TITLE
Please provide an AppImage

### ISSUE THREAD

**Issue by Simon-Laux** [inkle/inky#209]
https://appimage.org/
This might need an upgrade of the build/package system to https://github.com/electron-userland/electron-forge

**Comment by obradovicgoran** [comment]
Fully support AppImage or Snap installation package. On Ubuntu 19.10 I am getting segmentation fault when trying to launch the Inky editor.

**Comment by lunarcloud** [comment]
Actually, an AppImage could be built pretty easily with an additional script once a normal Linux build is done. No need to change build tools necessarily, unless they provide it for you.
I did something like it for [this project](https://github.com/lunarcloud/rpg-maker-vx-installer-scripts)

**Comment by lunarcloud** [comment]
This can be closed, sorry I didn't use the magic words ( "Fix #000" ) in my pull request for github to auto-close it
