### ISSUE TITLE
`.command` files should have a shebang

### ISSUE THREAD

**Issue by facelesspanda** [inkle/inky#211]
When using fish shell on linux, `RUN.command` and `INSTALL_AND_RUN.command` fail with
```
The file <file_name> is marked as an executable but could not be run by the operating system.
```

A fix is to use a shebang `#!/usr/bin/env sh` but it makes it platform-dependent. I don't know if it works on mac (it should?). On windows the run steps are already different, so it doesn't change that.

**Comment by joethephish** [comment]
Cool, yeah that works on Mac too! Have added the shebang in b6a485319fa142b7b862198c714a3fad995f6e8b.
