### ISSUE TITLE
Web Export is broken

### ISSUE THREAD

**Issue by DarkYagami** [inkle/inky#212]
In Inky version 0.11.0 Web Export still works fine, but gives me this warning:
internal/process/warning.js:18 (node:10101) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.

Now i downloaded the newest Inky version from GitHub and built it. When I try Web Export, it creates an empty directory and gives me an error:
fs.js:129 Uncaught NodeError: Callback must be a function
    at maybeCallback (fs.js:129:9)
    at Object.writeFile (fs.js:1137:14)
    at fs.readFile (/home/yadayada/Downloads/UNALTERED-INKY/inky-master/app/renderer/inkProject.js:283:16)
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)

This seems like a bug, unless I somehow built Inky incorrectly(?)
(Linux Mint 19.1 Tessa, Xfce)

**Comment by joethephish** [comment]
Oops, good catch, thank you! Fixed in eb6282d1dc4609ab19d373c74f0a608097d9c890.

**Comment by DarkYagami** [comment]
Great, thanks!

Also thanks for the zoom feature. I was waiting for that one.
