### ISSUE TITLE
File name issue on case sensitive OS such as linux

### ISSUE THREAD

**Issue by boltomli** [inkle/inky#216]
`theintercept.ink` is referenced as `theIntercept.ink` so inky fails to start. Rename or link the file can resolve the problem.

```
app/main-process/ink/longer-ink-snippets/theintercept.ink -> app/main-process/ink/longer-ink-snippets/theIntercept.ink
```

**Comment by joethephish** [comment]
Whoops, thank you! Fixed in 1ce5846a1c30f98c79ce96a7302a00fbfb400ff1
