### ISSUE TITLE
Any way to make the Editor dark?

### ISSUE THREAD

**Issue by Orionis90** [inkle/inky#221]
The blinding white makes it difficult in the long run, would love a dark mode.

**Comment by JBingrun** [comment]
Hey, I found there is an option to switch light mode and dark mode in newer version. You just download the source code and build it. Than you will see it under View / Theme / Dark.

![註解 2020-01-21 144833](https://user-images.githubusercontent.com/6387498/72782141-fe0b4d00-3c5d-11ea-93e4-96bea46e46ab.png)

**Comment by lunarcloud** [comment]
Also, while I enjoy @paulloz 's dark theme work, the scrollbars (at least when I've been using it) are still blindingly bright, so there's improvements/tweaks that could be done.
