### ISSUE TITLE
Installing and running from source code may cause npm link errors

### ISSUE THREAD

**Issue by carsendecker** [inkle/inky#240]
When attempting to run the `INSTALL_AND_RUN `command on Mac, npm might create some errors like this:
<img width="731" alt="Screen Shot 2020-04-01 at 3 04 39 PM" src="https://user-images.githubusercontent.com/43142066/78593304-4537c180-77fb-11ea-9e9a-0445716e1ea0.png">

This was fixed through running `npm link [cmd]` where `[cmd]` is the missing command listed at the beginning of the error message. In this case, `markdown-html`. This had to be done for at least 2 different commands before it would run properly. 

While I don't think this is necessarily something that needs to be fixed in inky, it should be a part of some sort of documentation or troubleshooting guide to supplement the very brief build instructions in the README.

**Comment by joethephish** [comment]
I'm confused. I'm not an expert at all with node/npm but I've never run an `npm link` before. I wonder if there's some other step that could also have fixed it on my machine?

(The markdown html thing was done by a contributor so I don't fully understand the setup TBH!)

**Comment by carsendecker** [comment]
I hadn't either, and it could very well be an issue just with my computer setup. I was also required to run link for the electron module as well. Although, it could still possibly be useful to mention somewhere in case this might happen to others.

**Comment by lunarcloud** [comment]
I ran this on a clean virtual machine of MacOS High Sierra with node and didn't have this issue.
Never seen npm link before

**Comment by joethephish** [comment]
Okay, going to close this for now, unless new evidence emerges!
