### ISSUE TITLE
Save state breaks when Ink source file is modified.

### ISSUE THREAD

**Issue by Tayruh** [inkle/inky#253]
This is being resumed from the issue mentioned [here](https://github.com/inkle/inky/pull/236#issuecomment-610675968).

The issue that I'm reporting is that when you save the state, then modify your Ink source file, and then attempt to reload that state, your game will crash. This is due to the way that Ink assigns locations to choices and gathers in an incremental manner. Adding or removing a choice or gather will put it out of sync with your old save state. This would make it very difficult to update older lines of game script without breaking everyone's save file.

I initially thought this was an issue with just the HTML version due to the way that using it as an embedded system in something like Unity most likely has you entering at label points instead of restoring the state. However, I'm not sure that's the case, since it looks like visit counts are also tracked in the same manner.

This error report is based on my ability to reliably recreate the error described using the steps below. My assessment of the cause is from browsing the `story` variable using the javascript console. If I am way off base in any of my assumptions, please let me know and I will close the issue.

Please forgive the flood of images. Using them made it a lot clearer than copying and pasting the console output.

--- 

To replicate the issue, first start with a really simple ink story.
```
Begin the test.
* Initial choice.
    Choice text.
- -> END
```
The javascript and HTML with save/loading I'm using is from [here](https://github.com/inkle/ink/issues/547). The javascript places the value of `inkjs.Story(storyContent)` into `inkgame.story`, which I will be using to track the values. I'm able to see the issue using the original "export to web" files using the `storyContent` variable as well.

If you begin the story and then output the data of `inkgame.story._currentChoices` to the console, you'll get this.

![image](https://user-images.githubusercontent.com/48899805/78820555-01cd8680-79a6-11ea-9d5c-164c32eac8f7.png)

If you select the choice and then output the data of `inkgame.story._state.outputStream` to the onsole, you'll see this.

![image](https://user-images.githubusercontent.com/48899805/78820034-27a65b80-79a5-11ea-9146-a2178369633a.png)

Notice how in both instances, the choice is marked as `c-0`. I believe that `0` is the root, so `0.c-0` is the first choice.

The `inkgame.story.visitCounts` also tracks it this way. `0.g-0` must be the divert to `-> END`.

![image](https://user-images.githubusercontent.com/48899805/78821090-ed3dbe00-79a6-11ea-8320-d98f0da1d23f.png)

---

Now, if we change the test script to this instead and then re-run the same tests, we get different values, as expected. For the test, choose "Initial choice" again.

```
Begin the test.
* Failure test.
    Fail.
* Initial choice.
    Choice text.
- -> END
```
![image](https://user-images.githubusercontent.com/48899805/78821656-d481d800-79a7-11ea-9a4a-fdf4e44d7500.png)

![image](https://user-images.githubusercontent.com/48899805/78821833-19a60a00-79a8-11ea-936f-c2513f6d92c8.png)

![image](https://user-images.githubusercontent.com/48899805/78821901-33dfe800-79a8-11ea-8612-7a501f4b9cde.png)

As you can see, "Failure test" has become `c-0` and "Initial test" has become `c-1`. 

---

Look what happens when we change the first line to: `- Begin the test`

![image](https://user-images.githubusercontent.com/48899805/78823055-127ffb80-79aa-11ea-8a45-dc67fd374182.png)

The choices are now under a gather, and so they're `0.g-0.c-0` and `0.g-0.c-1`.

And for even more clarity, you can see the same indentifiers in the `storyContent` variable that you load into `inkjs.Story()`.

![image](https://user-images.githubusercontent.com/48899805/78824608-a357d680-79ac-11ea-9bbe-81186b2e0e45.png)

This is a major problem when you're saving the state and then reloading it after making changes. Adding or removing a single choice or gather breaks your saved game.

---

Entering a story via a label seems to be safe, since it associates the all its data with the label name and not an index like the above examples. (I used a label named `test` in this example.)

![image](https://user-images.githubusercontent.com/48899805/78826231-2aa64980-79af-11ea-83e2-e90f14b164e7.png)

![image](https://user-images.githubusercontent.com/48899805/78826270-3d208300-79af-11ea-9fa4-11cd330b0f99.png)

I guess the only issue that would remain if you relied upon labels would be that `*` choice counts would not be tracked correctly, so hidden choices might not be hidden? I'm not sure on that.

Anyway, I think that's enough wall of text and images. I'm sure you get the idea by now.

(Tagging @joningold to resume the conversation.)

**Comment by joningold** [comment]
So as mentioned on the other thread, ink is pretty robust to this.
Obviously it can’t ever be completely robust; if you try to load a save
from game A into game B, it won’t cope.

The general rules are for maintaining save compatibility after a game has
been released are:

- don’t delete choices, instead add a conditional {false} to choices you
want to remove
- avoid restructuring weaves. When writing a story it’s a good idea to
break into stitches at intervals to ensure you have “safe” chunks
- in general if ink can’t find the exact story location where it saved it
looks up the tree for the nearest match and goes there instead.
- don’t save inside a tunnel unless you’re super careful (if you change the
label of a piece of content up the stack it might cause a crash on
returning from the tunnel which might be after the point of loading)


-- 
Jazz, in Three-Four Time: A Novel
http://www.amazon.co.uk/dp/B004K1EYIE

**Comment by Tayruh** [comment]
Thanks. That's what I thought the situation was, which is why I didn't report it in the past.

Should I close this issue, or should I leave it open for documentation purposes?

**Comment by joningold** [comment]
I’d prefer we close it since it’s kinda overly general - the general case
isn’t possible to solve - but if there are specific cases we should be
catching better, or ideas to improve the edge cases, then it’d be good to
raise those as specific issues.

Thanks!
-- 
Jazz, in Three-Four Time: A Novel
http://www.amazon.co.uk/dp/B004K1EYIE

**Comment by Tayruh** [comment]
Okay. Thanks for the quick responses. 🙂 

Closing the issue now.
