### ISSUE TITLE
Need advice : custom theme for new keywords

### ISSUE THREAD

**Issue by Darenn** [inkle/inky#255]
Hi!
Thanks for the software it's great.

I'm using it in my game and created some custom keywords as you can see in this screenshot :
![image](https://user-images.githubusercontent.com/11272715/78983222-15066080-7b24-11ea-96a0-ffff3a4354c1.png)

I would like to modify Inky so that my keywords like '*' '</wait>' or '>>>' appears in a different color.

I'm a bit lost in the codebase, maybe you can hint me in the right direction to do it? I found the file inkTheme.css that seems to change how it looks.

Thanks a lot.

**Comment by lunarcloud** [comment]
css? Are you using godot engine or the web export?

If the web export, write some javascript inside the "main.js" somewhere around line 109 that parses the innerHTML for your syntax, and builds a new span around the text with a special CSS class. Then you can define that CSS class in "style.css".

**Comment by lunarcloud** [comment]
So unless you want to change the preview pane in the editor, you shouldn't need to modify the project code (inkTheme.css). You can do it all after exporting.

**Comment by Darenn** [comment]
Thanks for your answer @lunarcloud . :D
Sorry I might have not explain my need very well.

My writer uses Inky only to write the story and previewing it. Then in my Game Engine (Godot) I compile the written story and use it in the game. I added some special keywords and symbols that are read later by the game when getting each ink line. For example putting a word between '*' will render it in italic in the game.

I want to modify the color of these symbols in the inky text editor directly not in the export.
For example I would like all '*' to appear in orange, then all '>' to appear in purple etc. It's for helping my writer clearly see what's special keyword and what's not.

**Comment by lunarcloud** [comment]
Seems like you need to do some parsing in, my best guess, 'playerView.js'

**Comment by Darenn** [comment]
Ok, I'll look into it and post my findings.

Thanks again!

**Comment by Darenn** [comment]
Done! Thanks a lot. 
I will post how I found out, in case anyone wants to do the same.

# RTFM
First you might want to read this [tutorial](https://ace.c9.io/#nav=higlighter) about **ACE**, a lib used by Inky.

# Add your rule and define your token
In [app/renderer/ace-ink-mode/ace-ink.js](https://github.com/inkle/inky/blob/master/app/renderer/inkFile.js) add your own rule into the rules. I've added mine into the *#mixedContent* part, to be sure that my changes works in *choices* and that i'm not overriding anything else (it's used last I think).

![image](https://user-images.githubusercontent.com/11272715/79004780-bd80e880-7b55-11ea-888a-1be2e149de16.png)

Some info from the tutorial, *regex* is your rule, *token* is the name that will be used by the span tags.

# Change the style of your token
Then go to [app/renderer/inkTheme.css](https://github.com/inkle/inky/blob/master/app/renderer/inkTheme.css) and add style for your token. The name is your token prefixed with '*span.ace_*', for me it was '*span.ace_link*'.

![image](https://user-images.githubusercontent.com/11272715/79005119-83641680-7b56-11ea-8709-11d97cca616a.png)

# Enjoy
Compile, run, and there you go! Here's what it look like with my special keywords added in light blue.

![image](https://user-images.githubusercontent.com/11272715/79005345-f077ac00-7b56-11ea-9e38-c05479fc9b24.png)

**Comment by joethephish** [comment]
Nicely done! This makes me wonder whether we could allow the user to inject their own rules in a preferences dialogue, that could be handy!

**Comment by Darenn** [comment]
Yes it would be very useful! Even the tutorial advises to add some custom keyword for your games like that, so I think many of us do it.

Removing these custom keyword from the preview would be a good thing too!

But it was very hard me for me to find out how to do this (never touched web dev JS/Electron/NodeJS) so I'll let someone else do it. :p

**Comment by Darenn** [comment]
Sorry to bother you again @joethephish @lunarcloud.
I can't find where the npm install put the executable on windows...

**Comment by lunarcloud** [comment]
If I want the executable, I usually run BUILD_FOR_WINDOWS.bat which makes a build at the top of the project

**Comment by Darenn** [comment]
Yeah I thought npm install would work.
I looked into BUILD_FOR_WINDOWS.bat t and found out that it was this one to execute.
Note that you need to install electron packager for that (`npm install electron-packager -g`)
Then the build will be available in .zip.
Thanks again! :)
