### ISSUE TITLE
Inky should be the default program to open .ink files

### ISSUE THREAD

**Issue by carsendecker** [inkle/inky#258]
On MacOS, Inky is not set as the default program to open .ink files. It would be good to be able to just double-click an ink file to automatically open it in Inky instead of something like TextEdit that defaults to the highest priority.

**Comment by carsendecker** [comment]
Ok, I might be a little dense but I'm unsure if its because I am fiddling with the LSHandlerRank or because it did this all along. Double-clicking an ink file is opening Inky, but TextEdit is still being displayed under "Open With" as the default program?

**Comment by jeremydouglass** [comment]
On my macOS 10.12.6 + Inky 0.11, .ink defaults to Inky.

**Comment by carsendecker** [comment]
Might be a niche issue, however I noticed in the program's info.plist inky is set only as an "Alternate" instead of Default or Owner. It is easy enough for me to tweak, so if possible I can still pull request the tiny change for consistency's sake unless it was set to Alternate for a reason.

**Comment by joethephish** [comment]
Feel free to submit a pull request, this is definitely accidental!
