### ISSUE TITLE
Unreadable warning text in dark mode

### ISSUE THREAD

**Issue by DarkYagami** [inkle/inky#261]
In dark mode warnings are highlighted in the editor, but because the background color is so similar to the text color, the text basically becomes unreadable.

This can be fixed by adding this to dark.css:

.window.dark #editor .ace-warning {
    background-color: #7d6015;
}

(I would have done a pull request for this, but I don't understand Git and Git does not understand me. Sorry.)

**Comment by joethephish** [comment]
Thanks! Done in f0c1904ebbd7d8e1c4a685c99293f9953e406c61.
