### ISSUE TITLE
Adding a knot-count alert

### ISSUE THREAD

**Issue by hkajs** [inkle/inky#263]
Hello! 

I was wondering if adding a knot-count would be a helpful contribution. My reason for thinking this is it may be convenient to know how complex in terms of parts the story is.

**Comment by joethephish** [comment]
I like the idea of a statistics option. There’s already a word count but it’s not necessarily very accurate.

If I hooked something up to the ink compiler we could get a bunch of stats out easily and display it all in one place, and it would be nice and accurate.

**Comment by joethephish** [comment]
Statistics is now added in 670c4894b02b0f0adb546d01795bebf74d3cbb74.
