### ISSUE TITLE
Feature: web export "update story" option

### ISSUE THREAD

**Issue by joningold** [inkle/inky#28]
You've probably already considered this, but if a web folder already exists for a game, it'd be handy to have the option to just update the story.js file and leave the css and the rest intact -- in case you've hacked it. (Obviously, one can duplicate, but it's less elegant?)

**Comment by joethephish** [comment]
Yeah, I've considered it, it's just a question of how to do it elegantly.
It's probably just a matter of choosing good wording for the menu option.

**Comment by bitbutter** [comment]
Ah, great to see this is already being talked about! As far as wording for the export items in the menu here's a suggestion:

Export JSON ...
Export files for web ...
Export myStory.js ...

I liked the idea of the plural in 'files for web' to differentiate it from the other commands which would generate just a single file each.

The last item is the one for the functionality that doesn't currently exist. The 'myStory' part would dynamically reflect the current name of the document, i don't know how feasible that is.

**Comment by joethephish** [comment]
Yeah that sounds really good to me. I haven't investigated how easy it is to dynamically rename a menu item in Electron, but I'm sure it must be possible.

I was also wondering about using the word "Re-export" for the JS, so it doesn't confuse people who are exporting for the first time, and they don't end up with a JS file that they don't know what to do with.

**Comment by bitbutter** [comment]
That could work. Though I suppose someone opening that menu for the first time and seeing 'Re-export' might be confused (they didn't yet export anything).

One other alternative:

Export JSON ...
Export web directory ...
Export myStory.js for web ...

Perhaps the exported myStory.js file could include a comment explaining that it's supposed to be used in the context of the web directory export.

**Comment by joethephish** [comment]
Done, with a static menu option name for now to keep things simple: 4e02f5c2c8f922cf3cf859cc843b4adc5f6bc346.
