### ISSUE TITLE
Is there any way to Observe/Print Ink Variables in the Web Export?

### ISSUE THREAD

**Issue by omz85** [inkle/inky#284]
Hi, 

Very new to Ink/Inkle and programming in general here...

I'm not sure if this is possible or not but I want to create a crude "UI" within the Inkle web export to observe/track certain numerical variables (Health, etc) as they change within the Ink file based on choices the user is making so it's always at the "top" of the screen if that makes sense.

Any advice towards this (perhaps lofty) aim would be gratefully received.

Regards
omz

**Comment by Selsynn** [comment]
Can you also close this one, as you seem to have resolved your problem from Inkle/Ink repository?
