### ISSUE TITLE
Marking does not compile - Windows 10 (x64)

### ISSUE THREAD

**Issue by dgboy** [inkle/inky#285]
I ran the program in the preview window entered does not respond to the entered text. Why?
![image](https://user-images.githubusercontent.com/47785873/85604345-e3e4f900-b659-11ea-8e3d-31929aca7ea8.png)

**Comment by Selsynn** [comment]
I think it does not compile while the file is not saved with a proper name. 
I'm not sure, tho. It could be anything else, but that the first thing I see. Saving to a new file should be the first thing you do, even if it means you have to rename the file after.

**Comment by dgboy** [comment]
@Selsynn No, the problem is likely here. Since the other pc it works fine.
![image](https://user-images.githubusercontent.com/47785873/85624211-36321400-b672-11ea-95d9-d6fb9ec91d47.png)
but I still do not understand why inky does not work on my laptop...\

**Comment by Selsynn** [comment]
It seems you are trying to run inky / inklecate from inside the zip package?
Just unzip it and see if it resolves the problem.

If that's not the case, we will be one step closer to have it really working!

**Comment by dgboy** [comment]
@Selsynn Useless. It doesn't work and so and so.

**Comment by dgboy** [comment]
It works. I just took the compiler from the previous version.
