### ISSUE TITLE
plans for new release? (as of August 2020)

### ISSUE THREAD

**Issue by riidom** [inkle/inky#292]
Wanted to ask if there are any plans for a new release, which would include the new dark mode option.

**Comment by jlon125** [comment]
I am trying to build it myself from the latest commit, but I'm not able to. 

The last working windows build was in 2019. Can we get an update?

**Comment by manuq** [comment]
I would also love to see a new build for Linux. The one in [releases/tag/0.11.0](https://github.com/inkle/inky/releases/tag/0.11.0) does not work for me, and is very old.

Furthermore,  I am proposing to distribute Inky in [flathub.org](https://flathub.org/). This is a great way to reach all modern Linux desktops! For now I built from latest commit by running `BUILD_FOR_LINUX.sh` and uploaded the ZIP to [my fork of Inky](https://github.com/manuq/inky/releases/tag/alpha). I would love to get rid of that and point directly to this upstream repository from Flathub.

**Comment by lunarcloud** [comment]
There exists a new release: https://github.com/inkle/inky/releases/tag/0.12.0
Suggest this issue be closed.
