### ISSUE TITLE
Theme option not saving?

### ISSUE THREAD

**Issue by DJLink** [inkle/inky#295]
Hi,

So I grabbed from source and built inky, I can change the theme to Dark but everytime I close it loses the settings, is this supposed to be working or did I missed some build configs?

**Comment by StoryStratos** [comment]
Even in the new release 0.12.0, which has Dark theme stabilised as a feature, it doesn't save the theme between instances of inky (even if you open a second after setting the theme). Alternatively, using the system theme by default may work, but this is something that seems quite natural to preserve between sessions.
