### ISSUE TITLE
Did someone take over development?

### ISSUE THREAD

**Issue by Soothsilver** [inkle/inky#298]
I see there are many forks of Inky on GitHub but no new releases here.

Is there someone who forked inky and is adding multiple features to their copy and making releases?

**Comment by Kindleguy** [comment]
This is an open-source project. Of course there are many forks. The main developer is still Inkle Studios.
I think you should try to contact Inkle themselves if you want to know for sure, but I think Inkle simply have not had the time to make releases that are stable enough for everyone to use. I had to build the code myself to discover the new features, which was worth the build effort.

There are some annoying bugs like the one I reported today (#304) , so I think Inkle simply works for making Inky stable enough when they have time between their game development work.

**Comment by joningold** [comment]
It's still us.
