### ISSUE TITLE
thread_example from documentation not works. Do threads works at all?

### ISSUE THREAD

**Issue by And0k** [inkle/inky#299]
![image](https://user-images.githubusercontent.com/3835091/99981898-94465d00-2db2-11eb-9b47-7a19a01db4e2.png)
Just end of story

**Comment by Selsynn** [comment]
You have to go to the ```->thread_example``` before the declaration of the thread. Here you are just declaring the thread, not using it.

**Comment by And0k** [comment]
ok Thanks
