### ISSUE TITLE
Feature Request: Ability to disable autocomplete

### ISSUE THREAD

**Issue by spdrcstl** [inkle/inky#320]
**Suggestion**

Add either a simple on-off toggle to the Autocomplete feature, or else a modular one that allows for selective autocomplete of any of vocabulary, variables, and divert targets. 

Access to the dictionary of words the project has built up - similar to how Openoffice handles it, allowing removal of individual entries and disabling of adding new words to the list - would be an even better feature, but I expect this would be harder to implement than simple category toggles.

**Reasoning**

- Selective enable/disable of vocab, variables, and divert targets already possible via commenting out existing code, but not very user-friendly to do this method.
- Current autocomplete semi-frequently has false positives on common words _(screenshots 1 and 2)_
- Inclusion of a long string for whatever reason (dramatic effect of not using spaces, representation of encoded data, someone says the alphabet) then permanently becomes a false positive match for words _(screenshot 3)_
- When typing a script quickly, hitting enter to create a new line and accidentally replacing the last word with a diferent one - most noticeable with # tags, but also possible if the writer isn't using punctuation at the end of a line - gets frustrating very quickly.
- Also unsure how useful or not the Autocomplete feature is for non-english writers.

_Screenshot 1_
![Ink Autocomplete 1](https://user-images.githubusercontent.com/63952301/109426430-9e957a00-79e5-11eb-916e-d072c1e8a449.png)
_Screenshot 2_
![Ink Autocomplete 2](https://user-images.githubusercontent.com/63952301/109426432-9f2e1080-79e5-11eb-8ad3-addb2d5863c9.png)
_Screenshot 3_
![Ink Autocomplete 3](https://user-images.githubusercontent.com/63952301/109426528-0c41a600-79e6-11eb-9214-9aeb13a80bc0.png)

**Comment by jimthurston** [comment]
I'd like to second this request.  Loving inky so far but this is the one thing that's been annoying me since I started using it.  Thanks

**Comment by potatocubed** [comment]
I'd like to third this request please. The style of brevity quest requires minimal punctuation, and having to hit Esc at the end of every line got very old, very fast.

**Comment by iluminacos** [comment]
To those looking for a build with autocompletee disabled, setting _enableLiveAutocompletion_ to _false_ (line 26 of editorView.js in app/renderer) did the trick for me. 
Alternatively, you can set _this.exactMatch_ to _true_ (line 1296 of _ext-language_tools.js_ in app/renderer/acesrc) keeps the feature, but makes it way less intrusive.

**Comment by heyacfox** [comment]
First time user of inky ending up here after 5 minutes of usage, thinking "Wow, this experience is going to be rough because of this autocomplete feature. Where's the preferences menu to turn this off?" Google pointed me here.

**Comment by jnmccla** [comment]
Wanted to add that I would appreciate this option! It can be handy (being able to tab to complete knot names and whatnot) but I typed "0" and it autocompleted to "101" and "c" completed to "continue" (as some examples) which can be frustrating to deal with.

**Comment by larryboyko** [comment]
> To those looking for a build with autocompletee disabled, setting _enableLiveAutocompletion_ to _false_ (line 26 of editorView.js in app/renderer) did the trick for me. Alternatively, you can set _this.exactMatch_ to _true_ (line 1296 of _ext-language_tools.js_ in app/renderer/acesrc). It keeps the feature, but makes it way less intrusive.

This didn't work for me, and I'm finding inky pretty dealbreakingly unusable for the same reasons already cited here.

**Comment by joethephish** [comment]
Okay added an option in e3520839bb4b984672a55e3943c8819483867565, and set `exactMatch` to true in 1e290510763c7de3aa4b7bd1a554b58e71a5f6b7. Thanks for the suggestions, folks!

**Comment by larryboyko** [comment]
Thanks a million, @joethephish ! And thanks to everyone at inkle for providing such a useful tool for our use.
