### ISSUE TITLE
"Unresolved Variable" not a variable

### ISSUE THREAD

**Issue by ThatMalzan** [inkle/inky#340]
I am in the middle of writing something like this:
_=opts
+ (opt1) [{Tell me about Detroit.|Can you tell me about Detroit, again?}] 
{DM: Detroit is a city.|DM: As I said, Detroit is a city.'}_

(_DM_ being the character in the story replying to the player.) However the editor highlights " **_DM:_** " in green and marks it as an "Unresolved variable" error.

What can I do?

**Comment by JasonWarrenUK** [comment]
One thing leaps to mind, but I'm not sure if I'm right:

DM: might be being read as a conditional. So the way I read your code is that...

- You have variable text
- The first alternative will display if the player has visited the knot or stitch called DM
- Then the second alternative will follow the same pattern
