### ISSUE TITLE
Version 0.12 cannot be opened because the developer cannot be verified (MAC)

### ISSUE THREAD

**Issue by chimalsky** [inkle/inky#343]
<img width="430" alt="Screen Shot 2021-05-02 at 10 44 22 AM" src="https://user-images.githubusercontent.com/8240872/116817243-5c96ca80-ab33-11eb-96f0-3ec35adc5954.png">

Earlier version 0.11 works on MAC

**Comment by dwhiffing** [comment]
You can work around this by opening the Security & Privacy menu in System Preferences after clicking Cancel here.  You should see the option to "Open Anyway" in the bottom left.

**Comment by chimalsky** [comment]
I was able to do this with inky 0.11 but not 0.12

I did however find a workaround.

I went to Security & Privacy > General and at the bottom there's a section to allow certain developers. After failing to open 0.12 Inky the developer got added to this screen.
