### ISSUE TITLE
External Function Invocation Causes Inky Preview To Go Blank

### ISSUE THREAD

**Issue by marcus-robinson** [inkle/inky#357]
When adding an external function invocation to an ink file, the preview pane goes blank.
There are no errors in the Inky validation UI or in the developer tools console.

Based on this [documentation of external functions](https://github.com/inkle/ink/blob/master/Documentation/RunningYourInk.md#external-functions), I would expect that their invocation would be supported in the Inky editor.

Example Ink file that causes the preview pane to go blank:
```
EXTERNAL PlayNextFeedback()

Here is the invocation of an external function:
~PlayNextFeedback()

-> END
```
If you comment out the `~PlayNextFeedback()` line, the preview pane displays correctly.

Inky version: 0.12.0
ink version: 1.0
inkjs version: 1.10.2
OS: Win10

**Comment by Selsynn** [comment]
You have to create a stub/fallback function in the ink code. It will not be called from your full project, but your inky can't know what to do if there is no fallback function.
(I agree it's somewhat obscure in the documentation)

**Comment by marcus-robinson** [comment]
Got it, thanks for clarifying @Selsynn
