### ISSUE TITLE
[Feature request] Do # theme tag in inky export apply at the moment it runs

### ISSUE THREAD

**Issue by rubereaglenest** [inkle/inky#374]
Do # theme tag in inky export apply at the moment it runs. In the same way #CLEAR works right now.

That would allow us to do stories stylized with changes between light and darkness from one chapter to another. For example, that the first chapter happens in a cave, and you step into the light, and then the character fell unconscious and dreams dark again, etc.

Right now #  theme selects the style for the whole story, and cannot be changed on the fly inside the story.

Of course, that use of the tag should be followed by #CLEAR ??? Or not, it could be awesome to see the whole screen fade in a precise moment, something that is currently supported by the exported web.

Thanks.

**Comment by lunarcloud** [comment]
Neat idea. There's no reason to #CLEAR when this happens, the theme can fade between styles, as it does when the 'theme-switch' button is pressed. You'd have to use/copy the logic from the code hooked up to that 'theme-switch' button (and not from the initial 'setupTheme' function) in the mid-story tag handling code.

Though, if your story needs multiple themes, something more complex than switching light-to-dark-to-light, then maybe this is a custom job for just your game. Then you could do more than just a 'light' and 'dark' theme.

**Comment by lunarcloud** [comment]
Upon further thought, allowing the story writer to control this directly would be overriding the user preference (OS / browser preference, and then what the user decides to change it to with the button).

I feel like this is really a game-custom thing to decide to not respect the user's decision on light v dark. Not great for a default feature since folks get really upset having their screens go bright while reading at night.

**Comment by lunarcloud** [comment]
Here:
```
// CLASS: className
else if( splitTag && splitTag.property == "CLASS" ) {
	customClasses.push(splitTag.val);
}

// theme: light or dark
else if( splitTag && splitTag.property == "theme" ) {
	document.body.classList.add("switched");
	let currentlyDark = document.body.classList.contains("dark");
	if ((splitTag.val == "dark") != currentlyDark)
	{
		document.body.classList.toggle("dark");
	}
}

// CLEAR - removes all existing content.
// RESTART - clears everything and restarts the story from the beginning
```
That'll do you.

**Comment by rubereaglenest** [comment]
Yeah, you are right.

Thanks!
