### ISSUE TITLE
Zoom and Theme reset on closing the app

### ISSUE THREAD

**Issue by egordorogov** [inkle/inky#379]
Unless there is some kind of limitation, shouldn't Inky remember zoom level on app relaunch? I have several separate ink files throughout the project, and each one is opening with 100% zoom, which for me is too small on 1440p screen. Maybe there is a way to change some config file?

This also applies to light/dark theme for those who uses it.

Thanks!

**Comment by MichalBerlinger** [comment]
+1 to this. I am showing Inky to students using projector, moving between many files, and always I need to manually set zoom to 200%, so everyone sees it well again and again.

**Comment by lunarcloud** [comment]
Same - having to re-select "dark" and "150%" every time gets tiring

**Comment by lunarcloud** [comment]
This is fixed by ed0a3191cf7aa514862e8329ce58e76dcc26838f - so it'll be in the next release (however long that'll take to release) - bost thing to do is build the app yourself if you really need the feature.

**Comment by egordorogov** [comment]
Great, thank you for pointing this out! Awaiting next release then.
