### ISSUE TITLE
Import JSON from https://writer.inklestudios.com

### ISSUE THREAD

**Issue by davelowensohn** [inkle/inky#39]
I've been working on a story at https://writer.inklestudios.com and want to import the resulting JSON file into Inky so I can pick up where I left off & work locally. Is there a way to do this currently, or do I need to manually re-type my story from scratch using Ink syntax?

Awesome software BTW, I really enjoy the syntax & workflow.

**Comment by joethephish** [comment]
Apologies, the JSON isn't compatible - they're entirely different. So, I'm afraid you'll have to copy/paste it if you want to work in ink!

**Comment by joethephish** [comment]
Sorry not yet I'm afraid!

I'd definitely back up your JSON files, maybe at some point in the future something like this will be developed. But it's not 100% straightforward I'm afraid! inklewriter's format is very different from ink.

**Comment by Berdedwerdsmeth** [comment]
Gutted!


I will indeed, thank you. Yeah touch wood!


Thanks for the reply.

________________________________

**Comment by joethephish** [comment]
Hey! This weekend I built a converter, see if it works for you: https://www.inklestudios.com/inklewriter/to-ink/

**Comment by Berdedwerdsmeth** [comment]
Joe, you are an absolute diamond and a true gentleman!
It worked, despite my having 7,609 lines in my monster!

It's showing a few errors but it looks like they were things that were already broken in the story, such as typos in the markers.

You've just done me an absolutely massive service (and probably several other writers). 
Can I offer you some payment for your work?

**Comment by joethephish** [comment]
Oooh good point, I need to test more for edge cases where the story isn’t finished or has bugs. I only tested with some finished stories. Did you see any other issues than the typos in markers?

Anyway, glad you found it helpful! Payment isn’t necessary, though we do have a Patreon for ink of you’re interested: https://www.patreon.com/inkle

Thanks!

**Comment by Berdedwerdsmeth** [comment]
I haven't seen anything else yet - just errors by me which I'd previously missed - but I'll let you know.


Oh yes, will absolutely get on that!


Thank you again.

________________________________

**Comment by joethephish** [comment]
Great, thank you!
