### ISSUE TITLE
Theme doesnt save

### ISSUE THREAD

**Issue by mohakdev** [inkle/inky#406]
I know this problem is solved here https://github.com/inkle/inky/issues/342 but it still doesn't work on my computer for some reason here is some additional info
**VERSION: 0.12.0**
![explorer_TWEc7mEl5B](https://user-images.githubusercontent.com/73052518/163685567-d033078d-a6d8-457c-8cbc-4af116d30a7b.gif)

**Comment by Selsynn** [comment]
Did you rebuild it from scratch? I do believe the fix is not in the release yet. You have to build the app to get the latest fixes

**Comment by mohakdev** [comment]
No actually I downloaded the release. Can I know when will it be included in the release

**Comment by joethephish** [comment]
This is now fixed in the latest release (0.13.0).
