### ISSUE TITLE
abs is listed twice under Ink > Useful functions in 0.13.0

### ISSUE THREAD

**Issue by 13xforever** [inkle/inky#418]
![image](https://user-images.githubusercontent.com/36445/174062319-1f2d4689-8d4c-4f0a-9634-b80699955823.png)

First `Mathematics: abs` option actually inserts block comment snippet

**Comment by joethephish** [comment]
Oops, good catch! Fixed in 699c4b4c82af700077075dc3cfefe82a7daa7403
