### ISSUE TITLE
32bit Windows release build 

### ISSUE THREAD

**Issue by leebrarian** [inkle/inky#42]
Would it be possible to include both 64bit and 32bit Windows release builds? 

I don't know if there's a non-trivial technical or practical reason 32bit releases aren't currently provided, but being able to run Inky on Atom-based Windows 10 tablets for on-the-go developing would be awesome.

**Comment by joethephish** [comment]
Ah, I didn't realise that new 32 bit machines were still being produced. I'll add 32 bit build in the next release.

**Comment by joethephish** [comment]
Okay, [new release out now](https://github.com/inkle/inky/releases/tag/0.4.0) with 32 bit support :)

**Comment by leebrarian** [comment]
Fantastic! Thanks :)
