### ISSUE TITLE
Linux: Cannot execute inklecate_win.exe

### ISSUE THREAD

**Issue by Menti** [inkle/inky#43]
After fixing #20 I could finally launch Inky but it's still not working for me.

This is the error message that appears on the right half of Inky when I write: 

> Ink compiler had an unexpected error ☹
> 
> /home/user/Inky-linux-x64/resources/app.asar.unpacked/main-process/ink/inklecate_win.exe: /home/user/Inky-linux-x64/resources/app.asar.unpacked/main-process/ink/inklecate_win.exe: cannot execute binary file

And this is the terminal output:

> WRITING TO: /tmp/inky_compile/Untitled_ink_EliaOGQ/Untitled.ink
> Story exited unexpectedly with error code 126 (session 1)
> stderr: /home/user/Inky-linux-x64/resources/app.asar.unpacked/main-process/ink/inklecate_win.exe: /home/user/Inky-linux-x64/resources/app.asar.unpacked/main-process/ink/inklecate_win.exe: cannot execute binary file

I'm on openSUSE Leap 42.1.

Thanks!

**Comment by joethephish** [comment]
Do you have Wine installed? 

CC @kennethlarsen on this...

**Comment by kennethlarsen** [comment]
Yes, this does look like a Wine issues. 

If you have Wine installed please list the version (in terminal `wine --version`). 

Also, try to write for a bit in the editor. Does it compile after a while?

**Comment by Menti** [comment]
wine-1.8.2

No success waiting and writing more.

**Comment by kennethlarsen** [comment]
Hmm.. I cannot test this myself before next week but you could try upgrading to the development version of Wine and see if that's better until then.

**Comment by joethephish** [comment]
Also, just to rule it out, you might want to make sure that you aren't able to run inklecate on the command line. Try running this on the command line with no arguments:

`resources/app.asar.unpacked/main-process/ink/inklecate_win.exe`

**Comment by Menti** [comment]
> wine resources/app.asar.unpacked/main-process/ink/inklecate_win.exe
 >
 > ´╗┐Usage: inklecate2 <options> <ink file>
 >    -o <filename>:   Output file name
 >    -c:              Count all visits to knots, stitches and weave 
points, not
 >                     just those referenced by TURNS_SINCE and read counts.
 >    -p:              Play mode
 >    -v:              Verbose mode - print compilation timings
 >    -x <pluginname>: Use external plugin. 'ChoiceListPlugin' is only 
available plugin right now.
 >    -t:              Test mode - loads up test.ink
 >    -s:              Stress test mode - generates test content and
 >                     times compilation
 >    -k:              Keep inklecate running in play mode even after 
story is complete

**Comment by joethephish** [comment]
Ahha, so it does work in wine but you need to specifically call it with wine? (I really know nothing about linux...!)

**Comment by kennethlarsen** [comment]
I've seen this problem once where there were conflicting versions of Wine installed. Will have to look for a proper fix for this.

@joethephish it should call Wine automatically.

**Comment by kennethlarsen** [comment]
I think I found the problem. This is probably due to the fact that you don't have Wine 32bit installed. 

On deb* systems something like this:

`
    sudo dpkg --add-architecture i386
    sudo add-apt-repository ppa:wine/wine-builds
    sudo apt-get update
    sudo apt-get install --install-recommends winehq-devel
`

Not so familiar with openSUSE but perhaps there's something here: [https://en.opensuse.org/Wine](url)

**Comment by kennethlarsen** [comment]
@Menti Could you report whether this fix works for you or not?

**Comment by Menti** [comment]
Sorry; I tried it, and it didn't work. But I assume it was something on my part, possibly not having actually switched correctly from 64bit Wine to 32bit. I can't really tell.

**Comment by Paulloz** [comment]
Hi there, had the same problem (`.exe` file was running when called explicitly with `wine` but not otherwise).
Here's a workaround if your system is using `systemd`, create a file called `wine.conf` under `/etc/binfmt.d`. Write this inside:
```
# Start WINE on Windows executables
:DOSWin:M::MZ::/usr/bin/wine:
```
You should be good.

**Comment by Menti** [comment]
@Paulloz I've just tried your solution and it works! I myself don't have the slightest idea of what it does (I'm totally ignorant about systemd, other than knowing that my box is running it), but Inky in openSUSE is working for me now.

**Comment by Paulloz** [comment]
@Menti Well, it's only telling that a certain type of file should be executed with `wine`. You could also use this to be able to execute a `jar` by typing `./foo.jar` or a `mono` executable by typing `./bar.exe` etc.

**Comment by kennethlarsen** [comment]
@joethephish This can be closed now, I think. A reference for this issue would be helpful in the README.

**Comment by joethephish** [comment]
Cool - anyone want to open a pull request?

**Comment by Paulloz** [comment]
I can do this later today if needed.

**Comment by joethephish** [comment]
Thanks, now merged into master!
