### ISSUE TITLE
Mathematics: abs is shown twice

### ISSUE THREAD

**Issue by tomkail** [inkle/inky#443]
<img width="400" alt="Screenshot 2022-10-23 at 14 56 18" src="https://user-images.githubusercontent.com/1252816/197396298-0adc2268-0879-49c3-a498-bee6de70d200.png">

**Comment by joningold** [comment]
I don't see this in inky 0.14.1, so I assume this is fixed already?

**Comment by joethephish** [comment]
I do remember fixing something like this a while ago so I’m surprised you saw this even in a recent version @tomkail …

**Comment by tomkail** [comment]
Looks like I was on an older version! Closing!
