### ISSUE TITLE
It does't start when run build and run command file, MAC

### ISSUE THREAD

**Issue by kaworuyoshi** [inkle/inky#45]
I clone the repo and execute the INSTALL_AND_RUN.command and gave me this error:

`node ../build/createDocumentnavigation.js && markdown-html resources/Documentation/WritingWithInk.md -s resources/Documentation/documentation.css -o renderer/documentation/embedded.html

module.js:327
    throw err;
    ^

Error: Cannot find module 'mkdirp'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/miguelmaciel/Documents/GitHub/inky/build/createDocumentnavigation.js:2:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! inky@0.4.0 postinstall: `node ../build/createDocumentnavigation.js && markdown-html resources/Documentation/WritingWithInk.md -s resources/Documentation/documentation.css -o renderer/documentation/embedded.html`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the inky@0.4.0 postinstall script 'node ../build/createDocumentnavigation.js && markdown-html resources/Documentation/WritingWithInk.md -s resources/Documentation/documentation.css -o renderer/documentation/embedded.html'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the inky package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ../build/createDocumentnavigation.js && markdown-html resources/Documentation/WritingWithInk.md -s resources/Documentation/documentation.css -o renderer/documentation/embedded.html
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs inky
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls inky
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/miguelmaciel/Documents/GitHub/inky/app/npm-debug.log
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
`

**Comment by joethephish** [comment]
Apologies! Fixed in c1a9369f8cd4d434c1ac2a5630f79c10c05a544d.
