### ISSUE TITLE
Export to JSON... not working correctly.

### ISSUE THREAD

**Issue by allaze-eroler** [inkle/inky#48]
it seem the exporter doesn't work correctly, i constantly get an error like this message : "Sorry, could not save to X:\blah\blah\blah\blah.json"

i'm using the windows 64bits version of inky.

**Comment by joethephish** [comment]
Anyone else seeing this (or not seeing this!) on Windows?

**Comment by Julisep** [comment]
I´m not seeing this error, exporting works as expected.

Has your useraccount the permission to write to the folder?

**Comment by allaze-eroler** [comment]
nope, it doesn't work, even though i run as admonistrator... not only that, it's still in 0.37.8.0 version... i wonder why i couldn't get that version 0.4.0.... or maybe it was because the software is in a different folder? which that would explain why i can't save the file in different HDD/SSD what a such mystery!

**Comment by joethephish** [comment]
The 0.37.8.0 is actually the version number for Electron, on which Inky is based. I've got [a bug](https://github.com/inkle/inky/issues/47) for the Mac version of Inky adopting the Electron version number but I didn't realise the windows build was doing the same? Where did you see that?

Erm, anyhow, still not sure why you're getting the error I'm afraid!

**Comment by allaze-eroler** [comment]
since i couldn't find the version of software, i checked it by click right on the exe file and checked the properties, it's where i could find the version in details tab. 

for about the bug, i just realise that i forgot to mention which version of windows is, i'm using windows 7 pro 64 bits, French version (France). i hope it could help you out.

what i did is this: i open the software with the ink file which it's in the different HDD while the software is in my main SSD. once opened, i clicked file/export to JSON... that is how i got as message error.

**Comment by allaze-eroler** [comment]
i found a solution: i have to drag and drop on the software called inklecate which helped me to get the json file. you can find it from here: https://github.com/inkle/ink/releases you will be able to get that little app as inklescate zip for mac, windows and linux.

of course, it's only a temporary solution.

**Comment by codeartisticninja** [comment]
I have the same issue.. For some reason I can only export JSON to the C-Drive.. Using Windows 10 Pro..
I have can save the .ink-file and export to web on any drive..
