### ISSUE TITLE
The Filename is not sorted

### ISSUE THREAD

**Issue by alijaya** [inkle/inky#489]
Hello, my Inky file browser is not sorted by filename. I just want to know if this is intended behaviour?
![Screenshot 2023-08-23 at 12 27 00](https://github.com/inkle/inky/assets/74383/c8ad0c3d-f20e-4091-ad7c-178a02190333)

**Comment by joningold** [comment]
Files are sorted by the order of the INCLUDE statements in the main ink file. Moving these lines around will sort the file list.

**Comment by alijaya** [comment]
How about the Unused Files? Why it doesn't seem sorted? Or is there any way to sort the order of Unused Files?
