### ISSUE TITLE
Inky Development

### ISSUE THREAD

**Issue by zeltas** [inkle/inky#496]
...

**Comment by zeltas** [comment]
close issue as abandoned.

**Comment by jgravois** [comment]
they're a bit terse, but the README definitely has instructions for running the code in this repository locally.

https://github.com/inkle/inky#help-develop-inky

**Comment by zeltas** [comment]
> they're a bit terse, but the README definitely has instructions for running the code in this repository locally.
> 
>

That's really an understatement. You really don't know the other half of it.

**Comment by IFcoltransG** [comment]
If you've found a solution to your issue, please *don't* delete the text from your comments, because that means when reading the conversation we have to open past versions of the comments. Instead, *close* the issue so people know it's resolved.
