### ISSUE TITLE
Show folder in inky title.

### ISSUE THREAD

**Issue by SamTyurenkov** [inkle/inky#498]
Hi there,

I have a structure where different races have similar typical dialogues

ogres/about
humans/about
elves/about

Is there a way to see which folder a file belongs to? 
I need to maintain same naming because they are assigned via a script, so its not desired to rename them to ogre_about for example.

![image](https://github.com/inkle/inky/assets/19373777/c05a6985-b6d0-4652-9033-b9474e7c289a)

**Comment by Selsynn** [comment]
I'm not sure I understand your question very well. 
Do you mean when you are trying to include it, or just in the editor itself? 

If that's in the header of the editor (in the white on black part) I don't know any way to do it.

If that's the part in the menu, it should be already by folder, as soon as you include it. 
And if it is to include it in your ink script, it should also already work with the relative paths, so the folder it has.

**Comment by SamTyurenkov** [comment]
> If that's in the header of the editor (in the white on black part) I don't know any way to do it.
> 

Header of the editor and headers of each preview windows when switching between multiple instances of the editor. (On screenshot above I have 3 different files from 3 different folders)
