### ISSUE TITLE
Using inky in browser

### ISSUE THREAD

**Issue by Immortalin** [inkle/inky#50]
Hi! What should you do if you want to embed inky in a web app? I.e. not part of a desktop app

**Comment by Julisep** [comment]
The problem your idea has, is the fact that inky is written against a framework for running web-technologies (html, css, js etc.) without a browser ([electron](http://electron.atom.io/)).

To run inky in your browser you would have to something like
- remodelating the appmenu electron provides with html,
- combining the inner window of inky with this appmenu and
- providing everything with an framework like Express.

Then it would be able to run inky as web app, I beleive.

**Comment by joethephish** [comment]
You might want to take a look at [Quill](http://jeejah.xyz/quill/). [Source here](https://github.com/MattConrad/Quill). That does the compilation and playing on the server.

The ink runtime now has a [JavaScript implementation](https://github.com/y-lohse/inkjs) so could be *played* in a browser, but the compiler is still C# so needs to run on the server.

**Comment by Immortalin** [comment]
I see, thank you for your help!
