### ISSUE TITLE
Program Deletes Entire Project if You Rapidly Hit Ctrl + S

### ISSUE THREAD

**Issue by msala1203** [inkle/inky#508]
I was working on a project and finally completed it. In celebration I hit ctrl + S multiple times to save the it but everything disappeared. At first, I thought I might of accidently hit ctrl + a and then ctrl + x or something like that. I tried to undo and pasting it back, but no my project just disappeared. I wanted to recreate the issue so I go a different project, made a copy and hit followed the same steps. The project was again deleted. I'm not quite sure why this issue happens, but I wanted to let you know in case this happens to anyone else.

**Comment by joethephish** [comment]
We’d been aware of this happening to people, albeit quite rarely, but never found a solid way to reproduce it.

I’m really sorry this happened to you, but fingers crossed we can figure it out with this feedback, assuming we can reproduce it in the same way. Thank you!!

**Comment by joethephish** [comment]
Okay, I think there was something screwy going on with our file watcher (Chokidar). I added extra checks so that it doesn't auto-load files that are in the middle of being saved, and also made it so that you can't start multiple saves simultaneously. Fixed in 08731f17
