### ISSUE TITLE
Browser jumps to beginning of flow

### ISSUE THREAD

**Issue by papataci** [inkle/inky#54]
Hello everybody, i thought i already made an issue about this problem, but probably made something wrong, anyway...

In games exported for web whenever i click on a choice the browser window scrolls to the beginning of the flow then scrolls down again to the end, anybody experiences this problem?

**Comment by joethephish** [comment]
I haven't seen this in general usage. But I haven't tested the limits - do you have very long sections of text between choices by any chance? On 80 Days / Sorcery etc, we have a check that makes sure it never causes the top of a new section of text to scroll offscreen during a transition, but I haven't added that to the inky web template (yet).

**Comment by joethephish** [comment]
[This pull request](https://github.com/inkle/inky/pull/59) fixed a bug that sounds like this on Firefox. Perhaps that fixes it for you? Feel free to re-open if not.
