### ISSUE TITLE
Shuffle not exactly random

### ISSUE THREAD

**Issue by armzzz** [inkle/inky#55]
Hi there,

So I'm playing around with Inky for an HTML 5 hobby project. The idea behind it is that the game consists of a series of random encounters, during which a decision has to be made, and then the player gets sent into another random encounter. Here's the code I wrote to test the general structure: 
```
=== main_knot ===
= para001
Hi there!
This is a test of my random selector thingy for Armaan the Adventurer.
Hopefully it works out well!
-> adv_knot

=== adv_knot
VAR adventure = ->adv_knot
~adventure = roll_adv()
+ [Let's do this!] -> adventure
+ [I'm sick of adventuring, let's get out of here!] -> exit

= adv001
You've gone on to Adventure 001!
-> adv_knot

= adv002
And now here's Adventure 002!
-> adv_knot

= adv003
This here's Adventure 003!
-> adv_knot

= adv004
Adventure 004
-> adv_knot

= adv005
OMG we're on adventure 005!
-> adv_knot

= exit
-> END

=== function roll_adv ===
{   shuffle: 
            - ~return ->adv_knot.adv001 
            - ~return ->adv_knot.adv002 
            - ~return ->adv_knot.adv003 
            - ~return ->adv_knot.adv004
            - ~return ->adv_knot.adv005
}
```
Works almost perfectly, except the shuffle in the roll_adv() function isn't completely random. It will pick one at random, yes, but in repeated consecutive tries, every encounter is guaranteed to show up once.

So, I did five tries in a row, I'd get : 3, 5, 2, 1, 4
Then the next five came up: 2, 4, 1, 3, 5
And so on. 

Every group of five consecutive calls to roll_adv() will inevitably result in the numbers 1 through 5 showing up in random order. Is this a bug or intended functionality? Ideally I'd like it to produce truly random results.

**Comment by joethephish** [comment]
This is absolutely by design I'm afraid. It's a shuffle rather than a randomisation, intended to randomise the order, but to prevent the same piece of content being seen too frequently.

A random maths function seems like a sensible thing to add though, and I believe would be a popular addition (even if we wouldn't use it outselves).

In the meantime, you could achieve the effect with an external function? And have an ink fallback that uses a shuffle?

**Comment by armzzz** [comment]
An external function it is then! Thanks for the reply and keep up the great work :)
