### ISSUE TITLE
.nav-wrapper DIV hides itself...

### ISSUE THREAD

**Issue by royda** [inkle/inky#60]
(please delete or close if this is a preexisting issue...but I couldn't find any)

When I go to "View" menu and then "Toggle Developer Tools" and then "X" out of the developer tools, the "sidebar" on the left side slides upwards, making its items inaccessible. I'm guessing it's a CSS thing, but I can't put my finger on what. Thank  you.

EDIT: As a work-around, with Inky maximized, and **before** you open the developer tools, hide the sidebar using the sidebar button on the top left (looks like several horizontal lines), and then open the Developer Tools...do what you need to do, then close the Developer Tools and reopen the sidebar. It will work fine then.

**Comment by joethephish** [comment]
Hmm, I haven't managed to reproduce your issue, but would it help if you popped out the developer tools, so it doesn't affect the layout of inky's main view? i.e. press this button:

![image](https://cloud.githubusercontent.com/assets/858967/18412702/68660bfc-778d-11e6-951c-35592ce4a02e.png)

I think that setting should get saved between launches too.

**Comment by royda** [comment]
That did help quite a bit before the latest issue. I was going to make a video to show what's going on but downloaded the latest Inky. Now I can't open any *.ink file. Inky just sits there. Eventually I have to use Task Manager to close it out because "X" or exit doesn't work. Sigh. Anyways, I'll close this for now.

**Comment by joethephish** [comment]
Argh, sorry to hear that. Though I saw something similar and fixed it yesterday. I'll try to get a new version of inky out soon...

**Comment by royda** [comment]
Awesome! Thanks for your efforts, they are appreciated :) :+1:
