### ISSUE TITLE
Erasing of include files content (100% repro)

### ISSUE THREAD

**Issue by joningold** [inkle/inky#62]
steps:

1. make a new include file using the widget in the left hand pane.

    inky will take you that file 

2. type any content

3. select another file in the project  in the left pane

4. select the new include file in the left pane.

    The content you typed is gone.

Repeating this process now does *not* trigger the bug. Any content typed from here will be kept intact as expected. In practice, this means when you cut/paste code to refactor into an include file... always copy and paste!!

**Comment by joethephish** [comment]
Additional requirement: seems the project has to be saved before you started these steps.

**Comment by joethephish** [comment]
Fixed in b2e1550b15107a7975ff33c2ae40b84d4246d525, will be available in next release.
