### ISSUE TITLE
Compiler error on Linux Ubuntu

### ISSUE THREAD

**Issue by kennethlarsen** [inkle/inky#64]
Let's keep the debugging info here and not on [Twitter](https://twitter.com/eeease/status/780400970949943296)

A user get the following error:
![inkyerror](https://cloud.githubusercontent.com/assets/1408595/18837879/b82c96fe-8405-11e6-98d9-b0db142e69d4.png)

He's using Linux Ubuntu 16.04.1 with Wine 1.9.19

I am currently trying to debug this.

**Comment by challsted** [comment]
@kennethlarsen any update on this?
Im having similar issues with Fedora 24, just opened Inky for the first time. 

Using wine-1.9.20 (Staging)

**Comment by kennethlarsen** [comment]
@challsted Hmm.. It's working on my Fedora build. Do you have Wine 32bit installed? That did the trick for me on Fedora. 

I just got a Ubuntu distro running so I'll do some more debugging on this error soon. Let me know if it works for you. 

And just to make sure: Please try writing something in the editor like:

> Will you crash?
> * Yes
> * No

and then just wait a minute. Sometimes it actually comes around.

**Comment by challsted** [comment]
@kennethlarsen hmm... I'm not seeing anything in the depos that separate out the wine stuff other then x86_64 (which if I'm thinking correctly thats multilib and supports 32 and 64)
and i see i686 (i think this is a specific arcitecture) 

everything else i see after executing `dnf search wine` is all extras, but none of them SEEM to be for 32bit (please correct me if I'm wrong!)

Also, as you suggested, i entered the above text, and in about 10 seconds it appears as needed :)

I guess i can work though the errors as i have time then, instead of stressing about them, thanks for your suggestion and good luck in your debugging! 

Also, strangely, after i closed, and reopened Ink, i no longer see these errors after doing the above... strange...

**Comment by kennethlarsen** [comment]
@challsted Did you see if the error text were actually just 'warnings' from Wine telling you about experimental stuff? Or was it actual errors as in the screenshot? 
As you might have guessed - Wine is reeeeally acting strangely with the Inky compiler :)

**Comment by challsted** [comment]
It was 3 things it was complaining about
i honestly cant recall what was the first section of stuff
the 2nd was that XDG_DATA_HOME and XDG_???_??? was not set, so i needed to set them manually (not sure why, but my XDG Values are not set by default... i had to set XDG_CONFIG_HOME recently)
the 3rd was all wine things

didnt take the time to pay too much attention to the specifics as i assumed it wouldnt go away...

**Comment by kennethlarsen** [comment]
@challsted Thanks anyway! Let me know if you run into other issues.

**Comment by davduf** [comment]
Sorry for this basic question... but how do you install Inky on Linux Ubuntu 16.04 ?
All my very best !

**Comment by kennethlarsen** [comment]
@davduf By following the instructions in the [readme](https://github.com/inkle/inky#linux)

Let me know if you run into any issues.

**Comment by davduf** [comment]
Oh Thank you so much !
I didn't see.
Now, I hace to install node.js on my ubuntu but I don't know how...

My very best !

Le mar 3 jan 2017 à 6:57, Kenneth Larsen <notifications@github.com> a 
écrit :

**Comment by davduf** [comment]
Well well well... I did the install as you mentioned https://github.com/inkle/inky/releases/tag/0.6.4
Everything works, except that inky is very slow, much more than on my mac, et make my (new) computer very hot... 
I am on Ubuntu 10.04 + Gnome Shell 3.18
Thanx!
David

**Comment by davduf** [comment]
I have to add, i get sometimes this message:

> Ink compiler had an unexpected error ☹ Application tried to create a window, but no driver could be loaded. Make sure that your X server is running and that $DISPLAY is set correctly.
Ink compiler had an unexpected error ☹ err:systray:initialize_systray Could not create tray window
 
I don't know if it could help you ?

**Comment by arashikou** [comment]
I ran into this same issue, as well as the extreme slowness and CPU churn. But I have managed to resolve all of them, and I hope my experience can shed some light on what is going on. (Or at least help others suffering from the same.)

My system is running Ubuntu 14.04.5 LTS. I had Wine 1.6.2 installed on my system at the time I first tried Inky on it. I did not have Mono installed. I was getting the DISPLAY error mentioned above, however Inklecate would eventually work if given enough time. Inklecate's performance was abysmally slow, making Inky's preview pane near-useless.

On a gut feeling, I tried installing Mono. Installing Mono, for whatever reason, fixed the issues for me. I stopped getting errors from Wine, and Inky became about as responsive as it is on Windows. I am not well-versed in Wine or Mono, but my guess is that Wine was running the program in some emulation of .NET before I had Mono installed but deferred to Mono once it was available.

Some support for this idea: I initially got an older version of Mono (3.2.8) from my package manager. Installing this version of Mono actually caused a different error to supercede the Wine error, and it also prevented previewing from working at all. The error, for reference:

```
Unhandled Exception:
System.TypeLoadException: A type load exception has occurred.
  at Ink.CommandLineTool.Main (System.String[] args) [0x00000] in <filename unknown>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: A type load exception has occurred.
  at Ink.CommandLineTool.Main (System.String[] args) [0x00000] in <filename unknown>:0 
```

Adding the Xamarin repos to my system [as outlined on the Mono site](http://www.mono-project.com/download/) and installing the latest version of the package mono-complete from them (4.6.1.5) is what fixed all my problems.

**Comment by davduf** [comment]
Dear  arashikou 

Thank you so much for taking time to write this.
I am not familiar with Mono. Do you talk about install Mono on your Ubuntu or under Wine ? 

Thank you again!
David

**Comment by arashikou** [comment]
Mono is an open-source, cross-platform implementation of the .NET Framework developed by Xamarin. I am not sure exactly what its relationship to Wine is, (see previous comment about not being a Wine or Mono guru) but it is something you would install into Ubuntu directly, not under Wine. You can find installation instructions on their website: http://www.mono-project.com/download/

**Comment by davduf** [comment]
I will try. Did you see any improvements with Mono ?
My very best
David

**Comment by arashikou** [comment]
Yes. Sorry if that got lost in the details. Installing Mono is what fixed the problem for me. I no longer got errors, Inky's performance improved to a usable level, and my CPU usage went way down.

**Comment by davduf** [comment]
Thank you so much John !
How can I know i did well the installation of Mono ?
I am not sure...

Thank you !
David

Le jeu 12 jan 2017 à 14:17, John W. Bruce <notifications@github.com> a 
écrit :

**Comment by arashikou** [comment]
I'm happy to keep helping you, @davduf, but I'm not sure this Inky bug report is the best place to have this conversation. I've created a [gist](https://gist.github.com/arashikou/737dc37571466737038802051bcc4291) where we can continue our discussion. To be quite honest, you're hitting the boundaries of my very limited Mono knowledge, so you might also have better luck asking that question over at [Mono's own forum](http://mono.1490590.n4.nabble.com/).

**Comment by davduf** [comment]
Back again :-)
First, happy new year to all!

I am under Fedora 27 now.
I'd like to install and run Inky 0.8.0
I d/l https://github.com/inkle/inky/releases/tag/0.8.0

But when i launch Inky
I get this:

`Ink compiler had an unexpected error ☹

fixme:winediag:start_process Wine Staging 2.20 is a testing version containing experimental patches.
fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.
End of story`

Any idea ?

Thank you so much!
All my best

David

**Comment by ce60** [comment]
I got this: 

* Assertion at class.c:5597, condition `!mono_loader_get_last_error ()' not met

Ink compiler had an unexpected error ☹

Stacktrace:

  at  <0xffffffff>
  at Ink.CommandLineTool.Main (string[]) <0x00023>
  at (wrapper runtime-invoke) .runtime_invoke_void_object (object,intptr,intptr,intptr) <0xffffffff>

Native stacktrace:

	/usr/bin/mono() [0x8105b4a]
	[0xb774ad38]
	[0xb774ad50]
	/lib/i386-linux-gnu/libc.so.6(gsignal+0x47) [0xb753f687]
	/lib/i386-linux-gnu/libc.so.6(abort+0x143) [0xb7542ab3]
	/usr/bin/mono() [0x8288b23]
	/usr/bin/mono() [0x8288bb3]
	/usr/bin/mono() [0x816b4d1]
	/usr/bin/mono(mono_class_get_full+0xff) [0x816bdff]
	/usr/bin/mono(mono_class_from_name+0x107) [0x816c237]
	/usr/bin/mono(mono_class_from_typeref+0x190) [0x816b9a0]
	/usr/bin/mono(mono_class_get_full+0x164) [0x816be64]
	/usr/bin/mono(mono_class_get+0x1f) [0x816bf4f]
	/usr/bin/mono(mono_metadata_parse_mh_full+0x45c) [0x81b29fc]
	/usr/bin/mono(mono_method_get_header+0xbf) [0x819130f]
	/usr/bin/mono() [0x80666b2]
	/usr/bin/mono() [0x8068de4]
	/usr/bin/mono() [0x8069aee]
	/usr/bin/mono() [0x8106d17]
	[0xb773603e]
	[0xb74fc03e]
	/usr/bin/mono() [0x8069bf0]

I am running i686 machine and  have just installed Mono on Mint 17.2 Cinnamon 2.6.13

**Comment by lunarcloud** [comment]
i686 machine, meaning 32bit? So you need #156 resolved to use the Linux build instead of the Windows build via wine?

**Comment by lunarcloud** [comment]
This is all pretty old, I'd suggest closing this issue.
