### ISSUE TITLE
Example from tutorial produce no output in the preview panel

### ISSUE THREAD

**Issue by fireton** [inkle/inky#74]
This code:
```
=== hurry_home ===
We hurried home <> 
-> to_savile_row 

=== to_savile_row ===
to Savile Row 
-> as_fast_as_we_could

=== as_fast_as_we_could ===
<> as fast as we could.
-> DONE
```
shows nothing in the game preview panel. Only "End of story" is there.

Inky 1.4.3, Windows 7 64 bit.

**Comment by joethephish** [comment]
Apologies, we changed the way that ink works so that you always need to divert into the first knot. So you'll need `-> hurry_home` at the top. Reworking the documentation is definitely on the list of things we need to do, but unfortunately we're really busy on our next game right now!

**Comment by fireton** [comment]
Ok then! It's not a bug, just an undocumented feature! :)
