### ISSUE TITLE
Confused about knot at the start

### ISSUE THREAD

**Issue by nicholasderk** [inkle/inky#75]
I'm having an issue starting my work in Ink as it won't allow me to put a knot at the beginning, can anyone let me know what I'm missing?

The following works fine, I can play it in the right-hand pane and it ends properly after I've made a selection:
```
- This is a line of dialogue.
*   This is option one
*   This is option two
- This is a gather from those lines of dialogue. -> END
```

However, simply by adding a knot called start to the beginning of this, the right-hand pane only shows "End of Story" and will not let me play through or rewind to the start:
```
=== start
- This is a line of dialogue.
*   This is option one
*   This is option two
- This is a gather from those lines of dialogue. -> END
```

I assume I'm missing something very basic, as if I copy and paste The Intercept Ink script into Inky, it allows me to play it just fine, but it does have a knot for the beginning of the story (for the debug menu to divert to if it's enabled). Any help would be appreciated.

**Comment by joethephish** [comment]
Just put -> start at the very top :)
