### ISSUE TITLE
Options do not transition to target Knot in Web exports?

### ISSUE THREAD

**Issue by heyuser** [inkle/inky#76]
Hello

Has anybody seen the following behaviour after an Export to Web?

1. Text and related options render in browser as expected
2. Selecting an option refreshes the text instead of displaying the target text (in its own Knot), and strips the options.

In this case, each option should be leading to a target Knot.

The structure of the source is:

> ==top_knot==
> Block of copy
> 
> * option 1 copy -> targetknot1
> * option 2 copy -> targetknot2
> -> DONE
> 
> ==targetknot1==
> Copy1
> ->DONE
> 
> ==targetknot2==
> Copy2
> ->DONE

The same source works fine in Inky (OSX) preview.
Tested in OSX Safari and Win Chrome, Firefox, Edge -- all with the same results.

Hopefully am not missing anything obvious. Can anybody confirm or explain?

**Comment by mesotron** [comment]
Hm. On my build (0.6.3, Win64) that source does not run in preview unless I add

-> top_knot

as the first line. After doing so it runs fine for me both in preview as well as in export to web (Chrome).

**Comment by heyuser** [comment]
Thanks for looking into it and posting @mesotron . Adding ->top_knot per your advice didn't change anything for my target browsers, but seems like good idea.

I did find the root cause, and it turns out that it would not have been evident in my sample. The issue was using knot/divert names that started with numbers.

So:
-> 1targetknot
which diverts to knot 
==1targetknot==
does not resolve for my web exports and caused the behaviour described above.

**Comment by joethephish** [comment]
Sounds like it could be an issue in inkjs then. We should probably try to demonstrate/reproduce the issue between ink and inkjs. Looping in @y-lohse

**Comment by y-lohse** [comment]
Indeed, it seems inkjs is to blame here. Tracking it here : https://github.com/y-lohse/inkjs/issues/46

**Comment by lunarcloud** [comment]
Tracked bug was closed years ago. Let's close this one.
