### ISSUE TITLE
Feature request: debug view to see the state of variables

### ISSUE THREAD

**Issue by rubereaglenest** [inkle/inky#92]
Hi,

I don't know if this is already in Inky, or if it has been already proposed, but, a debug view to see the state of variables could help a lot to test works.

Regards.

**Comment by joningold** [comment]
Try the "watch" command in the "Story" menu up top.  It bascially adds a
printout of a variable to the story log on the left-hand side.

cheers
jon

**Comment by rubereaglenest** [comment]
Awesome! Thanks!
