### ISSUE TITLE
Changes in ChoosePathString since February?

### ISSUE THREAD

**Issue by lhughes41** [inkle/inky#94]
Hi,
 Just updated to v0.7.4. Was on a v6 previously.  My code when call ChoosePathString fails now where it didn't.  (I call the method from python -> C++ so my error reporting is not quite as precise as you might like). Can you tell me anything that might have changed please in that method?  Like arguments in particular? I did a search of source and comments there and didn't spot anything right away. Hoping something springs to mind :-(

  Luke

**Comment by joethephish** [comment]
Yeah, `ChoosePathString` now takes optional arguments. The signature in C# is:

`public void ChoosePathString (string path, params object [] arguments)`

So, you should be able to just pass the path, but not sure how bindings to other languages would work with C#'s `params` feature. Maybe you need to pass an empty/null array?

**Comment by lhughes41** [comment]
Funny was just coming back to post that I had figured out the second argument exists! Thanks. Now I have to figure out what the heck to pass it. Thinking empty/null etc as well.. Going to go bash my head against 8-) :-(

**Comment by lhughes41** [comment]
OK for those who come after if doing python and calling ChoosePathString the workaround is to pass 'None' as second argument. So here is a sample piece of Python that seems to be working in 0.7.4 where _StoryI is my bound instance of a story object and knot_name is my knot name string:
   _StoryI.ChoosePathString(knot_name, None)

**Comment by takotab** [comment]
**update** I needed to do a double None. So:
_StoryI.ChoosePathString(knot_name, None, None)

**Comment by lhughes41** [comment]
Bless you @takotab for that followup. I just updated to 0.8.1 (use in python context) and was banging ny head on using one None till found this thread again and your most helpful comment.. fixed it! 
  Luke
