### ISSUE TITLE
Issue: "Learn More" in inky does not work

### ISSUE THREAD

**Issue by mehalon** [inkle/inky#99]
Hi, 
when I click in inky on "Help" and "Learn More", nothing happens. Is it supposed to open a link in the browser or something?

**Comment by mehalon** [comment]
Sorry, seems redundant with issue #69  (which is already from October 2016 however).

**Comment by triptych** [comment]
This bug is still here after 3 years? https://github.com/inkle/inky/blob/dc8a466d0d6304d67337bad24fc7b44d1eebd7d1/app/main-process/appmenus.js#L222

**Comment by lunarcloud** [comment]
This has been fixed. Please, close this.
